from __future__ import annotations

from dataclasses import dataclass, field


BUSINESS_AREAS = [
    {"id": "water-equipment", "label": "OneRoot Water & Equipment Rentals", "short": "Water & Equipment"},
    {"id": "cold-store-groceries", "label": "OneRoot Cold Store & Groceries", "short": "Cold Store & Groceries"},
    {"id": "laundry-services", "label": "OneRoot Laundry Services", "short": "Laundry"},
    {"id": "mobile-money", "label": "OneRoot Mobile Money Services", "short": "Mobile Money"},
    {"id": "rentals-apartments", "label": "OneRoot Rentals & Apartments", "short": "Apartments"},
    {"id": "fresh-foods-drinks", "label": "OneRoot Fresh Foods & Drinks", "short": "Fresh Foods & Drinks"},
    {"id": "kitchen", "label": "OneRoot Kitchen", "short": "Kitchen"},
    {"id": "shared-operations", "label": "OneRoot Shared Operations", "short": "Shared Operations"},
]
BUSINESS_AREA_OPTIONS = [(item["id"], item["label"]) for item in BUSINESS_AREAS]
BUSINESS_AREA_LABELS = {item["id"]: item["label"] for item in BUSINESS_AREAS}
BUSINESS_AREA_SHORT = {item["id"]: item["short"] for item in BUSINESS_AREAS}
INVENTORY_CATEGORY_LIBRARY = {
    "water-equipment": [
        "Water Supply",
        "Equipment & Construction Consumables",
    ],
    "cold-store-groceries": [
        "Frozen Foods & Proteins",
        "Groceries & Pantry",
        "Drinks & Refreshments",
        "Household & Cleaning",
        "Personal Care",
        "Baby Care",
        "Sanitary & Tissue Care",
        "Stationery & School Supplies",
    ],
    "laundry-services": [
        "Laundry - Clothing",
        "Laundry - Bedding & Linen",
        "Laundry - Curtains & Covers",
        "Laundry - Carpets & Rugs",
        "Laundry - Upholstery",
        "Laundry - Footwear & Bags",
        "Laundry - Vehicle Fabrics",
        "Laundry - General Items",
    ],
    "mobile-money": [
        "Value Added Services",
    ],
    "rentals-apartments": [
        "Rent",
        "Monthly Bills",
        "Security Deposit",
        "Maintenance Charge",
    ],
    "fresh-foods-drinks": [
        "Drinks & Refreshments",
        "Frozen Treats",
        "Snacks & Confectionery",
    ],
    "kitchen": [
        "Prepared Meals",
        "Soups & Stews",
        "Ingredients & Prep",
        "Kitchen Service Charges",
    ],
    "shared-operations": [
        "Service Charges",
        "Gift Cards",
        "Admin Supplies",
    ],
}

USER_ROLE_OPTIONS = [
    ("owner", "Owner"),
    ("admin", "Admin"),
    ("finance", "Finance"),
    ("operations", "Operations"),
    ("apartment-manager", "Apartment Manager"),
    ("sales-stock-operator", "Sales & Stock Operator"),
    ("cashier", "Cashier"),
    ("viewer", "Viewer"),
]
USER_ROLE_LABELS = dict(USER_ROLE_OPTIONS)
ROLE_DESCRIPTIONS = {
    "owner": "Full access to every module, reports, exports, and user accounts.",
    "admin": "Full day-to-day operating access including user account management.",
    "finance": "Finance, reports, audit trail, salaries, suppliers, cashbooks, and reconciliations.",
    "operations": "Operations workspace covering POS, stock, online orders, services, and field activity.",
    "apartment-manager": "Apartment rentals, deposits, maintenance, and related reporting.",
    "sales-stock-operator": "Sales and stock menus together with laundry tickets and equipment rentals.",
    "cashier": "Fast counter operations for POS, daily sales, and online order payment follow-up.",
    "viewer": "Read-only visibility across the dashboard, reports, search, and workbook tools.",
}
ROLE_ACCESS_KEYS = {
    "owner": {
        "dashboard",
        "reports",
        "search",
        "pos",
        "inventory",
        "online_orders",
        "workbook",
        "expenses",
        "sales",
        "budgets",
        "petty_cash",
        "petty_cash_budgets",
        "cashbook_entries",
        "ledger_entries",
        "mobile_money_reconciliations",
        "apartments",
        "security_deposit_records",
        "maintenance_records",
        "laundry_tickets",
        "equipment_rental_bookings",
        "salary_records",
        "purchase_orders",
        "suppliers",
        "asset_records",
        "forecast_plans",
        "recurring_controls",
        "pos_closeouts",
        "audit",
        "users",
    },
    "admin": {
        "dashboard",
        "reports",
        "search",
        "pos",
        "inventory",
        "online_orders",
        "workbook",
        "expenses",
        "sales",
        "budgets",
        "petty_cash",
        "petty_cash_budgets",
        "cashbook_entries",
        "ledger_entries",
        "mobile_money_reconciliations",
        "apartments",
        "security_deposit_records",
        "maintenance_records",
        "laundry_tickets",
        "equipment_rental_bookings",
        "salary_records",
        "purchase_orders",
        "suppliers",
        "asset_records",
        "forecast_plans",
        "recurring_controls",
        "pos_closeouts",
        "audit",
        "users",
    },
    "finance": {
        "dashboard",
        "reports",
        "search",
        "workbook",
        "expenses",
        "sales",
        "budgets",
        "petty_cash",
        "petty_cash_budgets",
        "cashbook_entries",
        "ledger_entries",
        "mobile_money_reconciliations",
        "salary_records",
        "purchase_orders",
        "suppliers",
        "audit",
    },
    "operations": {
        "dashboard",
        "reports",
        "search",
        "workbook",
        "pos",
        "inventory",
        "online_orders",
        "sales",
        "laundry_tickets",
        "equipment_rental_bookings",
        "purchase_orders",
        "maintenance_records",
    },
    "apartment-manager": {
        "dashboard",
        "reports",
        "search",
        "workbook",
        "apartments",
        "security_deposit_records",
        "maintenance_records",
        "sales",
    },
    "sales-stock-operator": {
        "dashboard",
        "reports",
        "search",
        "pos",
        "inventory",
        "online_orders",
        "sales",
        "laundry_tickets",
        "equipment_rental_bookings",
    },
    "cashier": {
        "dashboard",
        "reports",
        "search",
        "pos",
        "sales",
        "online_orders",
    },
    "viewer": {
        "dashboard",
        "reports",
        "search",
        "workbook",
    },
}

SUITE_NAMES = [
    "Peace",
    "Grace",
    "Joy",
    "Hope",
    "Faith",
    "Love",
    "Wisdom",
    "Unity",
    "Harmony",
    "Patience",
    "Blessing",
    "Kindness",
    "Victory",
    "Strength",
    "Comfort",
    "Glory",
    "Favor",
]

PAYMENT_METHODS = [
    "Cash",
    "Mobile Money",
    "Bank Transfer",
    "Card",
    "Credit",
    "Pay On Pickup",
    "Cash On Delivery",
]
RECEIPT_STATUSES = ["Uploaded", "Pending", "Not Required"]
OCCUPANCY_STATUSES = ["Occupied", "Vacant", "Reserved", "Maintenance", "Notice Given"]
RENT_CYCLES = [
    ("6-month", "6 Months"),
    ("12-month", "12 Months"),
    ("24-month", "24 Months"),
    ("custom", "Custom"),
]
RENEWAL_STATUSES = [
    ("Current", "Current"),
    ("Review Due", "Review Due"),
    ("Renewal Discussed", "Renewal Discussed"),
    ("Renewed", "Renewed"),
    ("Ending", "Ending"),
]
LAUNDRY_SERVICE_TYPES = [("Normal", "Normal"), ("Express", "Express")]
LAUNDRY_STATUSES = ["Received", "In Progress", "Ready", "Delivered", "Cancelled"]
LAUNDRY_DELIVERY_MODES = ["Walk-in", "Pickup", "Delivery", "Pickup / Delivery"]
EQUIPMENT_RENTAL_STATUSES = ["Booked", "Out", "Returned", "Cancelled"]
EQUIPMENT_CONDITIONS = ["Good", "Fair", "Damaged"]
LEDGER_PARTY_TYPES = [
    ("tenant", "Tenant"),
    ("customer", "Customer"),
    ("community-account", "Community Account"),
    ("other", "Other"),
]
LEDGER_ENTRY_TYPES = [
    ("charge", "Charge"),
    ("payment", "Payment Received"),
    ("deposit", "Deposit / Advance"),
    ("credit-note", "Credit Note"),
    ("adjustment-up", "Adjustment Up"),
    ("adjustment-down", "Adjustment Down"),
]
MOBILE_MONEY_PROVIDERS = [
    ("MTN Mobile Money", "MTN Mobile Money"),
    ("Telecel Cash", "Telecel Cash"),
    ("AirtelTigo Money", "AirtelTigo Money"),
    ("Other / Custom", "Other / Custom"),
]
PETTY_CASH_TRANSACTION_TYPES = [
    ("Float Top-Up", "Float Top-Up"),
    ("Restock Purchase", "Restock Purchase"),
    ("Transport", "Transport"),
    ("Cleaning & Supplies", "Cleaning & Supplies"),
    ("Maintenance Support", "Maintenance Support"),
    ("Staff Welfare", "Staff Welfare"),
    ("Refund / Reversal", "Refund / Reversal"),
    ("Miscellaneous", "Miscellaneous"),
]
CASHBOOK_ENTRY_TYPES = [
    ("Cash In", "Cash In"),
    ("Cash Out", "Cash Out"),
    ("Bank Deposit", "Bank Deposit"),
    ("Bank Withdrawal", "Bank Withdrawal"),
    ("Transfer", "Transfer"),
    ("Bank Charge", "Bank Charge"),
]
PURCHASE_ORDER_STATUSES = [
    ("Draft", "Draft"),
    ("Ordered", "Ordered"),
    ("Part Received", "Part Received"),
    ("Received", "Received"),
    ("Cancelled", "Cancelled"),
]
SALARY_PAYMENT_STATUSES = [
    ("Pending", "Pending"),
    ("Part Paid", "Part Paid"),
    ("Paid", "Paid"),
]
ASSET_CATEGORIES = [
    ("Equipment", "Equipment"),
    ("Appliance", "Appliance"),
    ("Furniture", "Furniture"),
    ("Electronics", "Electronics"),
    ("Tool", "Tool"),
    ("Vehicle / Transport", "Vehicle / Transport"),
    ("Property Fixture", "Property Fixture"),
    ("Other / Custom", "Other / Custom"),
]
ASSET_CONDITIONS = [("Excellent", "Excellent"), ("Good", "Good"), ("Fair", "Fair"), ("Poor", "Poor")]
ASSET_STATUSES = [
    ("In Use", "In Use"),
    ("In Storage", "In Storage"),
    ("Under Repair", "Under Repair"),
    ("Retired", "Retired"),
    ("Sold", "Sold"),
]
RECURRING_MODULE_TYPES = [
    ("expense", "Expense"),
    ("supplier-bill", "Supplier Bill"),
    ("maintenance-task", "Maintenance Task"),
    ("apartment-bill", "Apartment Bill"),
]
RECURRING_FREQUENCIES = [
    ("monthly", "Monthly"),
    ("quarterly", "Quarterly"),
    ("half-yearly", "Half-Yearly"),
    ("yearly", "Yearly"),
]
ACTIVE_STATES = [("active", "Active"), ("paused", "Paused")]
MAINTENANCE_PRIORITIES = [("Low", "Low"), ("Medium", "Medium"), ("High", "High"), ("Critical", "Critical")]
MAINTENANCE_STATUSES = [
    ("Open", "Open"),
    ("Scheduled", "Scheduled"),
    ("In Progress", "In Progress"),
    ("Completed", "Completed"),
]


@dataclass(slots=True)
class FieldDefinition:
    name: str
    label: str
    field_type: str = "text"
    required: bool = False
    options: list[tuple[str, str]] = field(default_factory=list)
    placeholder: str = ""
    step: str = "0.01"
    rows: int = 4


@dataclass(slots=True)
class ModuleDefinition:
    key: str
    label: str
    legacy_collection: str
    menu_group: str
    amount_field: str = ""
    date_field: str = ""
    month_field: str = ""
    title_field: str = ""
    status_field: str = ""
    fields: list[FieldDefinition] = field(default_factory=list)
    editable: bool = True


MODULES: dict[str, ModuleDefinition] = {
    "expenses": ModuleDefinition(
        key="expenses",
        label="Expenses",
        legacy_collection="expenses",
        menu_group="Finance",
        amount_field="amount",
        date_field="date",
        title_field="vendor",
        status_field="receiptStatus",
        fields=[
            FieldDefinition("businessAreaId", "Business Area", "select", True, BUSINESS_AREA_OPTIONS),
            FieldDefinition("date", "Date", "date", True),
            FieldDefinition("vendor", "Vendor", "text", True),
            FieldDefinition("category", "Category", "text", True),
            FieldDefinition("description", "Description", "textarea"),
            FieldDefinition("paymentMethod", "Payment Method", "select", True, [(m, m) for m in PAYMENT_METHODS]),
            FieldDefinition("receiptStatus", "Receipt Status", "select", True, [(m, m) for m in RECEIPT_STATUSES]),
            FieldDefinition("amount", "Amount", "number", True),
            FieldDefinition("notes", "Notes", "textarea"),
        ],
    ),
    "budgets": ModuleDefinition(
        key="budgets",
        label="Budget Planner",
        legacy_collection="budgets",
        menu_group="Finance",
        amount_field="budgetAmount",
        month_field="month",
        title_field="category",
        fields=[
            FieldDefinition("month", "Month", "month", True),
            FieldDefinition("businessAreaId", "Business Area", "select", True, BUSINESS_AREA_OPTIONS),
            FieldDefinition("category", "Category", "text", True),
            FieldDefinition("budgetAmount", "Budget Amount", "number", True),
            FieldDefinition("notes", "Notes", "textarea"),
        ],
    ),
    "sales": ModuleDefinition(
        key="sales",
        label="Daily Sales",
        legacy_collection="sales",
        menu_group="Finance",
        amount_field="amount",
        date_field="date",
        title_field="sourceLabel",
        status_field="sourceType",
        fields=[
            FieldDefinition("businessAreaId", "Business Area", "select", True, BUSINESS_AREA_OPTIONS),
            FieldDefinition("date", "Sales Date", "date", True),
            FieldDefinition("amount", "Amount", "number", True),
            FieldDefinition("sourceType", "Source Type", "text"),
            FieldDefinition("sourceLabel", "Source Label", "text"),
            FieldDefinition("notes", "Notes", "textarea"),
        ],
    ),
    "apartments": ModuleDefinition(
        key="apartments",
        label="Apartment Rentals",
        legacy_collection="rentals",
        menu_group="Property",
        amount_field="rentPaid",
        month_field="month",
        title_field="tenantName",
        status_field="occupancyStatus",
        fields=[
            FieldDefinition("month", "Month", "month", True),
            FieldDefinition("suite", "Suite", "select", True, [(name, name) for name in SUITE_NAMES]),
            FieldDefinition("occupancyStatus", "Occupancy", "select", True, [(x, x) for x in OCCUPANCY_STATUSES]),
            FieldDefinition("tenantName", "Tenant Name", "text"),
            FieldDefinition("tenantPhone", "Tenant Phone", "text"),
            FieldDefinition("tenantEmail", "Tenant Email", "text"),
            FieldDefinition("tenantAddress", "Tenant Address", "text"),
            FieldDefinition("tenantIdNumber", "Tenant ID / Ghana Card", "text"),
            FieldDefinition("emergencyContactName", "Emergency Contact Name", "text"),
            FieldDefinition("emergencyContactPhone", "Emergency Contact Phone", "text"),
            FieldDefinition("guarantorName", "Guarantor Name", "text"),
            FieldDefinition("guarantorPhone", "Guarantor Phone", "text"),
            FieldDefinition("occupantsCount", "Occupants Count", "number", False, step="1"),
            FieldDefinition("moveInDate", "Move-In Date", "date"),
            FieldDefinition("noticeDate", "Notice Date", "date"),
            FieldDefinition("moveOutDate", "Move-Out Date", "date"),
            FieldDefinition("leaseStartDate", "Lease Start Date", "date"),
            FieldDefinition("leaseEndDate", "Lease End Date", "date"),
            FieldDefinition("rentCycleType", "Rent Cycle", "select", True, RENT_CYCLES),
            FieldDefinition("rentCycleMonths", "Custom Cycle Months", "number", False, step="1"),
            FieldDefinition("rentCycleAmount", "Rent Cycle Amount", "number"),
            FieldDefinition("rentDue", "Rent Due", "number"),
            FieldDefinition("rentPaid", "Rent Paid", "number"),
            FieldDefinition("rentPaymentDate", "Rent Payment Date", "date"),
            FieldDefinition("rentPaymentMethod", "Rent Payment Method", "select", False, [(m, m) for m in PAYMENT_METHODS]),
            FieldDefinition("rentPaymentReference", "Rent Payment Reference", "text"),
            FieldDefinition("rentReceivedBy", "Rent Received By", "text"),
            FieldDefinition("rentCoverageStartDate", "Coverage Start", "date"),
            FieldDefinition("rentCoverageEndDate", "Coverage End", "date"),
            FieldDefinition("nextRentDueDate", "Next Rent Due", "date"),
            FieldDefinition("creditBroughtForward", "Credit / Advance B/F", "number"),
            FieldDefinition("waterBill", "Water Bill", "number"),
            FieldDefinition("toiletBill", "Toilet Bill", "number"),
            FieldDefinition("sweepingBill", "Sweeping / Gutter", "number"),
            FieldDefinition("wasteBill", "Waste Bill", "number"),
            FieldDefinition("customChargeLabel", "Custom Charge Label", "text"),
            FieldDefinition("customChargeAmount", "Custom Charge Amount", "number"),
            FieldDefinition("customChargeTwoLabel", "Second Custom Charge Label", "text"),
            FieldDefinition("customChargeTwoAmount", "Second Custom Charge Amount", "number"),
            FieldDefinition("billDueDate", "Bills Due Date", "date"),
            FieldDefinition("billAmountPaid", "Bills Paid", "number"),
            FieldDefinition("billPaymentDate", "Bills Payment Date", "date"),
            FieldDefinition("billPaymentMethod", "Bills Payment Method", "select", False, [(m, m) for m in PAYMENT_METHODS]),
            FieldDefinition("billPaymentReference", "Bills Payment Reference", "text"),
            FieldDefinition("billReceivedBy", "Bills Received By", "text"),
            FieldDefinition("arrearsBroughtForward", "Arrears B/F", "number"),
            FieldDefinition("lateFee", "Late Fee", "number"),
            FieldDefinition("securityDepositHeld", "Security Deposit Held", "number"),
            FieldDefinition("nextInspectionDate", "Next Inspection Date", "date"),
            FieldDefinition("rentReviewDate", "Rent Review Date", "date"),
            FieldDefinition("renewalDate", "Renewal Date", "date"),
            FieldDefinition("renewalStatus", "Renewal Status", "select", False, RENEWAL_STATUSES),
            FieldDefinition("notes", "Notes", "textarea"),
        ],
    ),
    "petty_cash": ModuleDefinition(
        key="petty_cash",
        label="Petty Cash",
        legacy_collection="pettyCash",
        menu_group="Finance",
        amount_field="amount",
        date_field="date",
        title_field="description",
        status_field="transactionTypeId",
        fields=[
            FieldDefinition("date", "Date", "date", True),
            FieldDefinition("businessAreaId", "Business Area", "select", True, BUSINESS_AREA_OPTIONS),
            FieldDefinition("transactionTypeId", "Transaction Type", "select", True, PETTY_CASH_TRANSACTION_TYPES),
            FieldDefinition("description", "Description", "text", True),
            FieldDefinition("amount", "Amount", "number", True),
            FieldDefinition("paymentMethod", "Payment Method", "select", False, [(m, m) for m in PAYMENT_METHODS]),
            FieldDefinition("notes", "Notes", "textarea"),
        ],
    ),
    "petty_cash_budgets": ModuleDefinition(
        key="petty_cash_budgets",
        label="Petty Cash Budgets",
        legacy_collection="pettyCashBudgets",
        menu_group="Finance",
        amount_field="budgetAmount",
        month_field="month",
        title_field="businessAreaId",
        fields=[
            FieldDefinition("month", "Month", "month", True),
            FieldDefinition("businessAreaId", "Business Area", "select", True, BUSINESS_AREA_OPTIONS),
            FieldDefinition("budgetAmount", "Budget Amount", "number", True),
            FieldDefinition("notes", "Notes", "textarea"),
        ],
    ),
    "salary_records": ModuleDefinition(
        key="salary_records",
        label="Salaries",
        legacy_collection="salaryRecords",
        menu_group="People",
        amount_field="amountPaid",
        month_field="month",
        title_field="staffName",
        status_field="status",
        fields=[
            FieldDefinition("month", "Month", "month", True),
            FieldDefinition("staffName", "Staff Name", "text", True),
            FieldDefinition("businessAreaId", "Business Area", "select", False, BUSINESS_AREA_OPTIONS),
            FieldDefinition("baseSalary", "Base Salary", "number"),
            FieldDefinition("bonus", "Bonus", "number"),
            FieldDefinition("deductions", "Deductions", "number"),
            FieldDefinition("amountPaid", "Amount Paid", "number"),
            FieldDefinition("paymentDate", "Payment Date", "date"),
            FieldDefinition("status", "Status", "select", False, SALARY_PAYMENT_STATUSES),
            FieldDefinition("notes", "Notes", "textarea"),
        ],
    ),
    "cashbook_entries": ModuleDefinition(
        key="cashbook_entries",
        label="Cashbook / Bankbook",
        legacy_collection="cashbookEntries",
        menu_group="Finance",
        amount_field="amount",
        date_field="date",
        title_field="accountName",
        status_field="entryType",
        fields=[
            FieldDefinition("date", "Date", "date", True),
            FieldDefinition("accountName", "Account", "text", True),
            FieldDefinition("entryType", "Entry Type", "select", True, CASHBOOK_ENTRY_TYPES),
            FieldDefinition("amount", "Amount", "number", True),
            FieldDefinition("paymentMethod", "Payment Method", "select", False, [(m, m) for m in PAYMENT_METHODS]),
            FieldDefinition("reference", "Reference", "text"),
            FieldDefinition("notes", "Notes", "textarea"),
        ],
    ),
    "purchase_orders": ModuleDefinition(
        key="purchase_orders",
        label="Procurement / Purchase Orders",
        legacy_collection="purchaseOrders",
        menu_group="Procurement",
        amount_field="totalAmount",
        date_field="date",
        title_field="supplierName",
        status_field="status",
        fields=[
            FieldDefinition("date", "Date", "date", True),
            FieldDefinition("businessAreaId", "Business Area", "select", False, BUSINESS_AREA_OPTIONS),
            FieldDefinition("supplierName", "Supplier Name", "text", True),
            FieldDefinition("itemSummary", "Item Summary", "textarea", True),
            FieldDefinition("totalAmount", "Total Amount", "number", True),
            FieldDefinition("status", "Status", "select", False, PURCHASE_ORDER_STATUSES),
            FieldDefinition("notes", "Notes", "textarea"),
        ],
    ),
    "laundry_tickets": ModuleDefinition(
        key="laundry_tickets",
        label="Laundry Job Tickets",
        legacy_collection="laundryTickets",
        menu_group="Services",
        amount_field="amountDue",
        date_field="ticketDate",
        title_field="customerName",
        status_field="status",
        fields=[
            FieldDefinition("ticketDate", "Ticket Date", "date", True),
            FieldDefinition("businessAreaId", "Business Area", "select", True, BUSINESS_AREA_OPTIONS),
            FieldDefinition("customerName", "Customer Name", "text", True),
            FieldDefinition("customerPhone", "Customer Phone", "text"),
            FieldDefinition("serviceType", "Service Type", "select", True, LAUNDRY_SERVICE_TYPES),
            FieldDefinition("itemSummary", "Item Summary", "textarea", True),
            FieldDefinition("pieces", "Pieces", "number", False, step="1"),
            FieldDefinition("amountDue", "Amount Due", "number", True),
            FieldDefinition("amountPaid", "Amount Paid", "number"),
            FieldDefinition("paymentDate", "Payment Date", "date"),
            FieldDefinition("paymentMethod", "Payment Method", "select", False, [(m, m) for m in PAYMENT_METHODS]),
            FieldDefinition("paymentReference", "Payment Reference", "text"),
            FieldDefinition("dueDate", "Due Date", "date"),
            FieldDefinition("readyDate", "Ready Date", "date"),
            FieldDefinition("deliveryMode", "Delivery Mode", "select", False, [(item, item) for item in LAUNDRY_DELIVERY_MODES]),
            FieldDefinition("status", "Status", "select", True, [(item, item) for item in LAUNDRY_STATUSES]),
            FieldDefinition("notes", "Notes", "textarea"),
        ],
    ),
    "equipment_rental_bookings": ModuleDefinition(
        key="equipment_rental_bookings",
        label="Equipment Rentals",
        legacy_collection="equipmentRentalBookings",
        menu_group="Services",
        amount_field="rentalFee",
        date_field="bookingDate",
        title_field="equipmentItem",
        status_field="status",
        fields=[
            FieldDefinition("bookingDate", "Booking Date", "date", True),
            FieldDefinition("businessAreaId", "Business Area", "select", True, BUSINESS_AREA_OPTIONS),
            FieldDefinition("equipmentItem", "Equipment Item", "text", True),
            FieldDefinition("customerName", "Customer Name", "text", True),
            FieldDefinition("customerPhone", "Customer Phone", "text"),
            FieldDefinition("rentalFee", "Rental Fee", "number", True),
            FieldDefinition("amountPaid", "Amount Paid", "number"),
            FieldDefinition("paymentDate", "Payment Date", "date"),
            FieldDefinition("paymentMethod", "Payment Method", "select", False, [(m, m) for m in PAYMENT_METHODS]),
            FieldDefinition("paymentReference", "Payment Reference", "text"),
            FieldDefinition("depositAmount", "Deposit Held", "number"),
            FieldDefinition("damageCharge", "Damage Charge", "number"),
            FieldDefinition("outDate", "Out Date", "date"),
            FieldDefinition("dueDate", "Due Date", "date"),
            FieldDefinition("returnDate", "Return Date", "date"),
            FieldDefinition("status", "Status", "select", True, [(item, item) for item in EQUIPMENT_RENTAL_STATUSES]),
            FieldDefinition("conditionOut", "Condition Out", "select", False, [(item, item) for item in EQUIPMENT_CONDITIONS]),
            FieldDefinition("conditionIn", "Condition In", "select", False, [(item, item) for item in EQUIPMENT_CONDITIONS]),
            FieldDefinition("reference", "Reference", "text"),
            FieldDefinition("notes", "Notes", "textarea"),
        ],
    ),
    "security_deposit_records": ModuleDefinition(
        key="security_deposit_records",
        label="Deposits & Tenant Charges",
        legacy_collection="securityDepositRecords",
        menu_group="Property",
        amount_field="depositPaid",
        date_field="captureDate",
        title_field="tenantName",
        status_field="status",
        fields=[
            FieldDefinition("captureDate", "Capture Date", "date", True),
            FieldDefinition("suite", "Suite", "select", True, [(name, name) for name in SUITE_NAMES]),
            FieldDefinition("tenantName", "Tenant Name", "text", True),
            FieldDefinition("tenantPhone", "Tenant Phone", "text"),
            FieldDefinition("depositExpected", "Deposit Expected", "number"),
            FieldDefinition("depositPaid", "Deposit Paid", "number"),
            FieldDefinition("depositPaymentDate", "Deposit Payment Date", "date"),
            FieldDefinition("chargesRaised", "Tenant Charges Raised", "number"),
            FieldDefinition("chargesPaid", "Tenant Charges Paid", "number"),
            FieldDefinition("chargePaymentDate", "Charge Payment Date", "date"),
            FieldDefinition("deductionFromDeposit", "Deduction From Deposit", "number"),
            FieldDefinition("refundDue", "Refund Due", "number"),
            FieldDefinition("refundPaid", "Refund Paid", "number"),
            FieldDefinition("refundPaymentDate", "Refund Payment Date", "date"),
            FieldDefinition("depositDueDate", "Deposit Due Date", "date"),
            FieldDefinition("refundDueDate", "Refund Due Date", "date"),
            FieldDefinition(
                "status",
                "Status",
                "select",
                True,
                [
                    ("Active Hold", "Active Hold"),
                    ("Part Paid", "Part Paid"),
                    ("Charge Follow-up", "Charge Follow-up"),
                    ("Refund Pending", "Refund Pending"),
                    ("Closed", "Closed"),
                ],
            ),
            FieldDefinition("notes", "Notes", "textarea"),
        ],
    ),
    "ledger_entries": ModuleDefinition(
        key="ledger_entries",
        label="Ledgers",
        legacy_collection="ledgerEntries",
        menu_group="Finance",
        amount_field="amount",
        date_field="entryDate",
        title_field="partyName",
        status_field="entryType",
        fields=[
            FieldDefinition("entryDate", "Entry Date", "date", True),
            FieldDefinition("businessAreaId", "Business Area", "select", True, BUSINESS_AREA_OPTIONS),
            FieldDefinition("partyType", "Party Type", "select", True, LEDGER_PARTY_TYPES),
            FieldDefinition("partyName", "Party Name", "text", True),
            FieldDefinition("partyPhone", "Party Phone", "text"),
            FieldDefinition("suite", "Suite / Reference", "text"),
            FieldDefinition("entryType", "Entry Type", "select", True, LEDGER_ENTRY_TYPES),
            FieldDefinition("amount", "Amount", "number", True),
            FieldDefinition("dueDate", "Due Date", "date"),
            FieldDefinition("reference", "Reference", "text"),
            FieldDefinition("notes", "Notes", "textarea"),
        ],
    ),
    "mobile_money_reconciliations": ModuleDefinition(
        key="mobile_money_reconciliations",
        label="Mobile Money Reconciliation",
        legacy_collection="mobileMoneyReconciliations",
        menu_group="Finance",
        amount_field="closingCashCounted",
        date_field="date",
        title_field="provider",
        fields=[
            FieldDefinition("date", "Date", "date", True),
            FieldDefinition("provider", "Provider", "select", True, MOBILE_MONEY_PROVIDERS),
            FieldDefinition("openingCash", "Opening Cash Float", "number", True),
            FieldDefinition("cashTopUp", "Cash Top-Up Added", "number"),
            FieldDefinition("cashRemoved", "Cash Removed", "number"),
            FieldDefinition("cashInValue", "Total Cash-In Value", "number"),
            FieldDefinition("cashOutValue", "Total Cash-Out Value", "number"),
            FieldDefinition("serviceFees", "Service Fees Earned", "number"),
            FieldDefinition("operatingExpense", "Operating Expense", "number"),
            FieldDefinition("closingCashCounted", "Closing Cash Counted", "number"),
            FieldDefinition("notes", "Notes", "textarea"),
        ],
    ),
    "suppliers": ModuleDefinition(
        key="suppliers",
        label="Suppliers",
        legacy_collection="suppliers",
        menu_group="Procurement",
        amount_field="amountDue",
        date_field="invoiceDate",
        title_field="supplierName",
        fields=[
            FieldDefinition("invoiceDate", "Invoice Date", "date", True),
            FieldDefinition("businessAreaId", "Business Area", "select", True, BUSINESS_AREA_OPTIONS),
            FieldDefinition("supplierName", "Supplier Name", "text", True),
            FieldDefinition("category", "Expense Type", "text"),
            FieldDefinition("itemDescription", "Item / Description", "textarea"),
            FieldDefinition("invoiceReference", "Invoice Reference", "text"),
            FieldDefinition("amountDue", "Amount Due", "number", True),
            FieldDefinition("amountPaid", "Amount Paid", "number"),
            FieldDefinition("dueDate", "Due Date", "date"),
            FieldDefinition("paymentDate", "Payment Date", "date"),
            FieldDefinition("paymentMethod", "Payment Method", "select", False, [(m, m) for m in PAYMENT_METHODS]),
            FieldDefinition("notes", "Notes", "textarea"),
        ],
    ),
    "asset_records": ModuleDefinition(
        key="asset_records",
        label="Assets",
        legacy_collection="assetRecords",
        menu_group="Admin",
        amount_field="currentValue",
        date_field="acquiredDate",
        title_field="assetName",
        status_field="status",
        fields=[
            FieldDefinition("acquiredDate", "Acquired Date", "date", True),
            FieldDefinition("businessAreaId", "Business Area", "select", True, BUSINESS_AREA_OPTIONS),
            FieldDefinition("assetName", "Asset Name", "text", True),
            FieldDefinition("assetCategory", "Asset Category", "select", True, ASSET_CATEGORIES),
            FieldDefinition("location", "Location", "text"),
            FieldDefinition("purchaseCost", "Purchase Cost", "number", True),
            FieldDefinition("currentValue", "Current Value", "number"),
            FieldDefinition("condition", "Condition", "select", True, ASSET_CONDITIONS),
            FieldDefinition("status", "Status", "select", True, ASSET_STATUSES),
            FieldDefinition("nextServiceDate", "Next Service Date", "date"),
            FieldDefinition("notes", "Notes", "textarea"),
        ],
    ),
    "forecast_plans": ModuleDefinition(
        key="forecast_plans",
        label="Forecast Plans",
        legacy_collection="forecastPlans",
        menu_group="Admin",
        amount_field="revenueTarget",
        month_field="month",
        title_field="businessAreaId",
        fields=[
            FieldDefinition("month", "Forecast Month", "month", True),
            FieldDefinition("businessAreaId", "Business Area", "select", True, BUSINESS_AREA_OPTIONS),
            FieldDefinition("revenueTarget", "Revenue Target", "number", True),
            FieldDefinition("expenseBudget", "Expense Budget", "number"),
            FieldDefinition("salaryBudget", "Salary Budget", "number"),
            FieldDefinition("notes", "Notes", "textarea"),
        ],
    ),
    "recurring_controls": ModuleDefinition(
        key="recurring_controls",
        label="Reminder Center",
        legacy_collection="recurringControls",
        menu_group="Admin",
        amount_field="amount",
        date_field="nextDueDate",
        title_field="title",
        status_field="activeState",
        fields=[
            FieldDefinition("title", "Control Name", "text", True),
            FieldDefinition("moduleType", "Module", "select", True, RECURRING_MODULE_TYPES),
            FieldDefinition("businessAreaId", "Business Area", "select", True, BUSINESS_AREA_OPTIONS),
            FieldDefinition("category", "Expense Type", "text"),
            FieldDefinition("counterparty", "Counterparty / Vendor", "text"),
            FieldDefinition("suite", "Suite / Location", "text"),
            FieldDefinition("amount", "Amount", "number"),
            FieldDefinition("frequency", "Frequency", "select", True, RECURRING_FREQUENCIES),
            FieldDefinition("startDate", "Start Date", "date"),
            FieldDefinition("nextDueDate", "Next Due Date", "date", True),
            FieldDefinition("lastGeneratedDate", "Last Generated Date", "date"),
            FieldDefinition("priority", "Maintenance Priority", "select", False, MAINTENANCE_PRIORITIES),
            FieldDefinition("activeState", "State", "select", True, ACTIVE_STATES),
            FieldDefinition("notes", "Notes", "textarea"),
        ],
    ),
    "maintenance_records": ModuleDefinition(
        key="maintenance_records",
        label="Maintenance",
        legacy_collection="maintenanceRecords",
        menu_group="Property",
        amount_field="actualCost",
        date_field="reportedDate",
        title_field="issue",
        status_field="status",
        fields=[
            FieldDefinition("reportedDate", "Reported Date", "date", True),
            FieldDefinition("businessAreaId", "Business Area", "select", True, BUSINESS_AREA_OPTIONS),
            FieldDefinition("location", "Location / Suite", "text"),
            FieldDefinition("assetItem", "Asset / Item", "text"),
            FieldDefinition("issue", "Issue / Task", "text", True),
            FieldDefinition("priority", "Priority", "select", True, MAINTENANCE_PRIORITIES),
            FieldDefinition("status", "Status", "select", True, MAINTENANCE_STATUSES),
            FieldDefinition("dueDate", "Due Date", "date"),
            FieldDefinition("estimatedCost", "Estimated Cost", "number"),
            FieldDefinition("actualCost", "Actual Cost", "number"),
            FieldDefinition("vendor", "Vendor / Technician", "text"),
            FieldDefinition("notes", "Notes", "textarea"),
        ],
    ),
    "online_orders": ModuleDefinition(
        key="online_orders",
        label="Online Orders",
        legacy_collection="onlineOrders",
        menu_group="Sales",
        amount_field="quotedTotal",
        date_field="createdAt",
        title_field="orderNumber",
        status_field="status",
        editable=False,
    ),
    "pos_closeouts": ModuleDefinition(
        key="pos_closeouts",
        label="POS Counter Closeouts",
        legacy_collection="posCounterClosures",
        menu_group="Sales",
        amount_field="totalAmount",
        date_field="orderDate",
        title_field="areaLabel",
        editable=False,
    ),
}

LEGACY_TO_MODULE = {definition.legacy_collection: definition.key for definition in MODULES.values()}
MODULE_TO_LEGACY = {definition.key: definition.legacy_collection for definition in MODULES.values()}

MENU_GROUPS = [
    (
        "Workspace",
        [
            ("Overview", ["dashboard", "reports", "search"]),
            ("Counter & Orders", ["pos", "online_orders", "workbook"]),
            ("Stock", ["inventory"]),
        ],
    ),
    (
        "Finance",
        [
            ("Sales & Spend", ["sales", "expenses", "budgets", "petty_cash", "petty_cash_budgets"]),
            ("Cash & Reconciliation", ["cashbook_entries", "ledger_entries", "mobile_money_reconciliations"]),
        ],
    ),
    (
        "Operations",
        [
            ("Apartments", ["apartments", "security_deposit_records", "maintenance_records"]),
            ("Service Desk", ["laundry_tickets", "equipment_rental_bookings"]),
            ("People & Supply", ["salary_records", "purchase_orders", "suppliers"]),
        ],
    ),
    (
        "Control",
        [
            ("Planning", ["forecast_plans", "recurring_controls", "pos_closeouts"]),
            ("Assets & Admin", ["asset_records", "audit", "users"]),
        ],
    ),
]
