from __future__ import annotations

from dataclasses import dataclass, field


BUSINESS_AREAS = [
    {"id": "water-equipment", "label": "OneRoot Water & Equipment Rentals", "short": "Water & Equipment"},
    {"id": "cold-store-groceries", "label": "OneRoot Cold Store & Groceries", "short": "Cold Store & Groceries"},
    {"id": "laundry-services", "label": "OneRoot Laundry Services", "short": "Laundry"},
    {"id": "mobile-money", "label": "OneRoot Mobile Money Services", "short": "Mobile Money"},
    {"id": "rentals-apartments", "label": "OneRoot Rentals & Apartments", "short": "Apartments"},
    {"id": "fresh-foods-drinks", "label": "OneRoot Fresh Foods & Drinks", "short": "Fresh Foods & Drinks"},
    {"id": "kitchen", "label": "OneRoot Kitchen", "short": "Kitchen"},
    {"id": "shared-operations", "label": "OneRoot Internal / Shared Operations", "short": "Internal"},
]
BUSINESS_AREA_OPTIONS = [(item["id"], item["label"]) for item in BUSINESS_AREAS]
BUSINESS_AREA_LABELS = {item["id"]: item["label"] for item in BUSINESS_AREAS}
BUSINESS_AREA_SHORT = {item["id"]: item["short"] for item in BUSINESS_AREAS}
INVENTORY_CATEGORY_LIBRARY = {
    "water-equipment": [
        "Water Supply",
        "Equipment Rental",
        "Construction Support",
        "Hand Tools",
        "Powered Tools",
        "Concrete & Masonry",
        "Equipment & Construction Consumables",
    ],
    "cold-store-groceries": [
        "Frozen Foods & Proteins",
        "Groceries & Pantry",
        "Drinks & Refreshments",
        "Household & Cleaning",
        "Personal Care",
        "Baby Care",
        "Sanitary & Tissue Care",
        "Stationery & School Supplies",
    ],
    "laundry-services": [
        "Laundry - Clothing",
        "Laundry - Bedding & Linen",
        "Laundry - Curtains & Covers",
        "Laundry - Carpets & Rugs",
        "Laundry - Upholstery",
        "Laundry - Footwear & Bags",
        "Laundry - Vehicle Fabrics",
        "Laundry - General Items",
    ],
    "mobile-money": [
        "Value Added Services",
    ],
    "rentals-apartments": [
        "Rent",
        "Monthly Bills",
        "Security Deposit",
        "Maintenance Charge",
    ],
    "fresh-foods-drinks": [
        "Drinks & Refreshments",
        "Frozen Treats",
        "Snacks & Confectionery",
    ],
    "kitchen": [
        "Prepared Meals",
        "Soups & Stews",
        "Ingredients & Prep",
        "Kitchen Service Charges",
    ],
    "shared-operations": [
        "Service Charges",
        "Gift Cards",
        "Admin Supplies",
    ],
}

USER_ROLE_OPTIONS = [
    ("owner", "Owner"),
    ("admin", "Platform Admin"),
    ("finance", "Finance & Controls"),
    ("operations", "Operations Manager"),
    ("apartment-manager", "Apartment Manager"),
    ("sales-stock-operator", "Sales & Stock"),
    ("cashier", "POS Cashier"),
    ("mobile-money-agent", "Mobile Money Agent"),
    ("laundry-desk", "Laundry Desk"),
    ("equipment-desk", "Equipment Desk"),
    ("delivery-dispatch", "Delivery & Dispatch"),
    ("marketing-crm", "CRM & Marketing"),
    ("hr-payroll", "HR & Payroll"),
    ("viewer", "Viewer"),
]
USER_ROLE_LABELS = dict(USER_ROLE_OPTIONS)
ROLE_DESCRIPTIONS = {
    "owner": "Full access to every module, reports, exports, and user accounts.",
    "admin": "Full day-to-day operating access including user account management, growth, dispatch, and controls.",
    "finance": "Finance controls, profits, salaries, suppliers, petty cash, cashbook, and reconciliations.",
    "operations": "Cross-area operations leadership for POS, inventory, services, online orders, mobile money, and dispatch.",
    "apartment-manager": "Apartment rentals, deposits, maintenance, and related reporting.",
    "sales-stock-operator": "Retail counter, stock handling, online order fulfillment, and day-end sales review.",
    "cashier": "Fast counter checkout, receipts, and daily POS sales follow-up.",
    "mobile-money-agent": "MTN MoMo service capture, float closeout, reconciliation, and mobile money sales review.",
    "laundry-desk": "Laundry intake, service payments, customer follow-up, and laundry day sales review.",
    "equipment-desk": "Equipment and water bookings, payments, rental follow-up, and service sales review.",
    "delivery-dispatch": "Online orders, dispatch coordination, delivery follow-up, and customer handover.",
    "marketing-crm": "Customer CRM, promotions, WhatsApp campaigns, campaign ROI, and repeat-customer growth.",
    "hr-payroll": "Payroll, attendance, vacancies, staff records, and internal knowledge/training controls.",
    "viewer": "Read-only visibility across the dashboard, reports, search, and workbook tools.",
}
ROLE_ACCESS_KEYS = {
    "owner": {
        "dashboard",
        "profits",
        "category_performance",
        "reports",
        "sales_summary",
        "search",
        "pos",
        "inventory",
        "inventory_barcode",
        "online_orders",
        "delivery_dispatch",
        "workbook",
        "expenses",
        "sales",
        "petty_cash",
        "petty_cash_budgets",
        "cashbook_entries",
        "mobile_money_transactions",
        "mobile_money_reconciliations",
        "apartments",
        "security_deposit_records",
        "maintenance_records",
        "laundry_tickets",
        "equipment_rental_bookings",
        "salary_records",
        "workforce_attendance",
        "job_vacancies",
        "knowledge_base",
        "suppliers",
        "customer_crm",
        "promotions",
        "whatsapp_campaigns",
        "campaign_roi",
        "asset_records",
        "forecast_plans",
        "recurring_controls",
        "pos_closeouts",
        "audit",
        "users",
    },
    "admin": {
        "dashboard",
        "profits",
        "category_performance",
        "reports",
        "sales_summary",
        "search",
        "pos",
        "inventory",
        "inventory_barcode",
        "online_orders",
        "delivery_dispatch",
        "workbook",
        "expenses",
        "sales",
        "petty_cash",
        "petty_cash_budgets",
        "cashbook_entries",
        "mobile_money_transactions",
        "mobile_money_reconciliations",
        "apartments",
        "security_deposit_records",
        "maintenance_records",
        "laundry_tickets",
        "equipment_rental_bookings",
        "salary_records",
        "workforce_attendance",
        "job_vacancies",
        "knowledge_base",
        "suppliers",
        "customer_crm",
        "promotions",
        "whatsapp_campaigns",
        "campaign_roi",
        "asset_records",
        "forecast_plans",
        "recurring_controls",
        "pos_closeouts",
        "audit",
        "users",
    },
    "finance": {
        "dashboard",
        "profits",
        "category_performance",
        "reports",
        "sales_summary",
        "search",
        "workbook",
        "expenses",
        "sales",
        "petty_cash",
        "petty_cash_budgets",
        "cashbook_entries",
        "mobile_money_transactions",
        "mobile_money_reconciliations",
        "salary_records",
        "workforce_attendance",
        "job_vacancies",
        "knowledge_base",
        "suppliers",
        "promotions",
        "campaign_roi",
        "forecast_plans",
        "audit",
    },
    "operations": {
        "dashboard",
        "profits",
        "category_performance",
        "reports",
        "sales_summary",
        "search",
        "workbook",
        "pos",
        "inventory",
        "inventory_barcode",
        "online_orders",
        "delivery_dispatch",
        "sales",
        "mobile_money_transactions",
        "laundry_tickets",
        "equipment_rental_bookings",
        "maintenance_records",
        "workforce_attendance",
        "job_vacancies",
        "knowledge_base",
        "customer_crm",
        "promotions",
        "whatsapp_campaigns",
        "forecast_plans",
    },
    "apartment-manager": {
        "dashboard",
        "profits",
        "category_performance",
        "reports",
        "sales_summary",
        "search",
        "workbook",
        "apartments",
        "security_deposit_records",
        "maintenance_records",
        "knowledge_base",
        "sales",
    },
    "sales-stock-operator": {
        "dashboard",
        "profits",
        "category_performance",
        "reports",
        "sales_summary",
        "search",
        "pos",
        "inventory",
        "inventory_barcode",
        "online_orders",
        "delivery_dispatch",
        "sales",
        "mobile_money_transactions",
        "laundry_tickets",
        "equipment_rental_bookings",
        "workforce_attendance",
        "knowledge_base",
        "customer_crm",
    },
    "cashier": {
        "dashboard",
        "profits",
        "category_performance",
        "reports",
        "sales_summary",
        "search",
        "pos",
        "sales",
        "online_orders",
        "mobile_money_transactions",
    },
    "mobile-money-agent": {
        "dashboard",
        "reports",
        "sales_summary",
        "search",
        "workbook",
        "sales",
        "cashbook_entries",
        "mobile_money_transactions",
        "mobile_money_reconciliations",
        "workforce_attendance",
        "knowledge_base",
    },
    "laundry-desk": {
        "dashboard",
        "reports",
        "sales_summary",
        "search",
        "workbook",
        "sales",
        "inventory",
        "laundry_tickets",
        "customer_crm",
        "workforce_attendance",
        "knowledge_base",
    },
    "equipment-desk": {
        "dashboard",
        "reports",
        "sales_summary",
        "search",
        "workbook",
        "sales",
        "inventory",
        "equipment_rental_bookings",
        "customer_crm",
        "workforce_attendance",
        "knowledge_base",
    },
    "delivery-dispatch": {
        "dashboard",
        "reports",
        "sales_summary",
        "search",
        "workbook",
        "online_orders",
        "delivery_dispatch",
        "customer_crm",
        "workforce_attendance",
        "knowledge_base",
    },
    "marketing-crm": {
        "dashboard",
        "reports",
        "search",
        "workbook",
        "online_orders",
        "customer_crm",
        "promotions",
        "whatsapp_campaigns",
        "campaign_roi",
        "knowledge_base",
    },
    "hr-payroll": {
        "dashboard",
        "reports",
        "search",
        "workbook",
        "salary_records",
        "workforce_attendance",
        "job_vacancies",
        "knowledge_base",
    },
    "viewer": {
        "dashboard",
        "profits",
        "category_performance",
        "reports",
        "search",
        "workbook",
    },
}

SUITE_NAMES = [
    "Peace",
    "Grace",
    "Joy",
    "Hope",
    "Faith",
    "Love",
    "Wisdom",
    "Unity",
    "Harmony",
    "Patience",
    "Blessing",
    "Kindness",
    "Victory",
    "Strength",
    "Comfort",
    "Glory",
    "Favor",
]

PAYMENT_METHODS = [
    "Cash",
    "Mobile Money",
    "Bank Transfer",
    "Card",
    "Credit",
    "Pay On Pickup",
    "Cash On Delivery",
]
RECEIPT_STATUSES = ["Uploaded", "Pending", "Not Required"]
OCCUPANCY_STATUSES = ["Occupied", "Vacant", "Reserved", "Maintenance", "Notice Given"]
RENT_CYCLES = [
    ("6-month", "6 Months"),
    ("12-month", "12 Months"),
    ("24-month", "24 Months"),
    ("custom", "Custom"),
]
RENEWAL_STATUSES = [
    ("Current", "Current"),
    ("Review Due", "Review Due"),
    ("Renewal Discussed", "Renewal Discussed"),
    ("Renewed", "Renewed"),
    ("Ending", "Ending"),
]
LAUNDRY_SERVICE_TYPES = [("Normal", "Normal"), ("Express", "Express")]
LAUNDRY_ITEM_CATEGORY_OPTIONS = [
    ("Clothing", "Clothing"),
    ("Bedding & Linen", "Bedding & Linen"),
    ("Curtains & Covers", "Curtains & Covers"),
    ("Carpets & Rugs", "Carpets & Rugs"),
    ("Upholstery", "Upholstery"),
    ("Footwear & Bags", "Footwear & Bags"),
    ("Vehicle Fabrics", "Vehicle Fabrics"),
    ("General Items", "General Items"),
]
LAUNDRY_STATUSES = ["Received", "In Progress", "Ready", "Delivered", "Cancelled"]
LAUNDRY_DELIVERY_MODES = ["Walk-in", "Pickup", "Delivery", "Pickup / Delivery"]
EQUIPMENT_RENTAL_CATEGORY_OPTIONS = [
    ("Equipment Rental", "Equipment Rental"),
    ("Water Delivery", "Water Delivery"),
    ("Hand Tools", "Hand Tools"),
    ("Powered Tools", "Powered Tools"),
    ("Concrete & Masonry", "Concrete & Masonry"),
    ("Construction Support", "Construction Support"),
]
EQUIPMENT_RENTAL_STATUSES = ["Booked", "Out", "Returned", "Cancelled"]
EQUIPMENT_CONDITIONS = ["Good", "Fair", "Damaged"]
LEDGER_PARTY_TYPES = [
    ("tenant", "Tenant"),
    ("customer", "Customer"),
    ("community-account", "Community Account"),
    ("other", "Other"),
]
LEDGER_ENTRY_TYPES = [
    ("charge", "Charge"),
    ("payment", "Payment Received"),
    ("deposit", "Deposit / Advance"),
    ("credit-note", "Credit Note"),
    ("adjustment-up", "Adjustment Up"),
    ("adjustment-down", "Adjustment Down"),
]
MOBILE_MONEY_PROVIDERS = [
    ("MTN Mobile Money", "MTN Mobile Money"),
    ("Telecel Cash", "Telecel Cash"),
    ("AirtelTigo Money", "AirtelTigo Money"),
    ("Other / Custom", "Other / Custom"),
]
MOBILE_MONEY_SERVICE_TYPES = [
    ("Cash In", "Cash In"),
    ("Cash Out", "Cash Out"),
    ("Send Money", "Send Money"),
    ("Receive Money / Remittance", "Receive Money / Remittance"),
    ("Merchant Pay / Bill Pay", "Merchant Pay / Bill Pay"),
    ("ECG / Utility Payment", "ECG / Utility Payment"),
    ("School Fees / Institutional Payment", "School Fees / Institutional Payment"),
    ("Airtime / Data", "Airtime / Data"),
    ("Wallet Top-Up", "Wallet Top-Up"),
    ("Bank To Wallet", "Bank To Wallet"),
    ("Wallet To Bank", "Wallet To Bank"),
    ("SIM Sale", "SIM Sale"),
    ("SIM Replacement", "SIM Replacement"),
    ("SIM Sale / Replacement", "SIM Sale / Replacement"),
    ("SIM Registration / Update", "SIM Registration / Update"),
    ("PIN Reset / Account Support", "PIN Reset / Account Support"),
    ("Statement / Balance Check", "Statement / Balance Check"),
    ("Other Service", "Other Service"),
]
MOBILE_MONEY_FLOAT_IMPACTS = [
    ("Cash In", "Cash In"),
    ("Cash Out", "Cash Out"),
    ("No Cash Movement", "No Cash Movement"),
]
MOBILE_MONEY_TRANSACTION_STATUSES = [
    ("Completed", "Completed"),
    ("Pending", "Pending"),
    ("Reversed", "Reversed"),
    ("Cancelled", "Cancelled"),
]
PETTY_CASH_TRANSACTION_TYPES = [
    ("Float Top-Up", "Float Top-Up"),
    ("Restock Purchase", "Restock Purchase"),
    ("Transport", "Transport"),
    ("Cleaning & Supplies", "Cleaning & Supplies"),
    ("Maintenance Support", "Maintenance Support"),
    ("Staff Welfare", "Staff Welfare"),
    ("Refund / Reversal", "Refund / Reversal"),
    ("Miscellaneous", "Miscellaneous"),
]
CASHBOOK_ENTRY_TYPES = [
    ("Cash In", "Cash In"),
    ("Cash Out", "Cash Out"),
    ("Bank Deposit", "Bank Deposit"),
    ("Bank Withdrawal", "Bank Withdrawal"),
    ("Transfer", "Transfer"),
    ("Bank Charge", "Bank Charge"),
]
SALARY_PAYMENT_STATUSES = [
    ("Pending", "Pending"),
    ("Part Paid", "Part Paid"),
    ("Paid", "Paid"),
]
SALARY_FREQUENCIES = [
    ("Monthly", "Monthly"),
    ("Biweekly", "Biweekly"),
    ("Weekly", "Weekly"),
    ("One-Off", "One-Off"),
]
STAFF_WORK_ROLES = [
    ("Manager", "Manager"),
    ("Operations Manager", "Operations Manager"),
    ("Business Manager & Operations Lead", "Business Manager & Operations Lead"),
    ("POS Cashier", "POS Cashier"),
    ("Stock Officer", "Stock Officer"),
    ("Mobile Money Agent", "Mobile Money Agent"),
    ("Laundry Desk Officer", "Laundry Desk Officer"),
    ("Equipment Rental Officer", "Equipment Rental Officer"),
    ("Front Desk / Service Desk Officer", "Front Desk / Service Desk Officer"),
    ("Stock & Dispatch Officer", "Stock & Dispatch Officer"),
    ("Apartment Manager", "Apartment Manager"),
    ("Dispatch Coordinator", "Dispatch Coordinator"),
    ("Delivery Rider", "Delivery Rider"),
    ("Kitchen Staff", "Kitchen Staff"),
    ("Finance Officer", "Finance Officer"),
    ("Finance, HR & Payroll Officer", "Finance, HR & Payroll Officer"),
    ("CRM & Marketing Officer", "CRM & Marketing Officer"),
    ("CRM, Marketing & Support Officer", "CRM, Marketing & Support Officer"),
    ("HR & Payroll Officer", "HR & Payroll Officer"),
    ("Support Staff", "Support Staff"),
]
STAFF_WORK_ROLE_LABELS = dict(STAFF_WORK_ROLES)
STAFF_ROLE_DESCRIPTIONS = {
    "Manager": "Senior owner or lead with broad day-to-day oversight.",
    "Operations Manager": "Supervises counter, services, dispatch, inventory, and daily controls.",
    "Business Manager & Operations Lead": "Leads the business and supervises daily operations across all business areas.",
    "POS Cashier": "Handles quick counter checkout, receipts, and basic customer payment flow.",
    "Stock Officer": "Updates products, quantities, barcode operations, and stock accuracy.",
    "Mobile Money Agent": "Captures MoMo services, commissions, float movements, and closeout.",
    "Laundry Desk Officer": "Receives laundry jobs, updates service progress, and captures payments.",
    "Equipment Rental Officer": "Books rentals, tracks due dates, and captures equipment payments.",
    "Front Desk / Service Desk Officer": "Handles POS, laundry intake, equipment rentals, receipts, and customer service at the front desk.",
    "Stock & Dispatch Officer": "Keeps stock accurate and coordinates item preparation and delivery handover.",
    "Apartment Manager": "Handles rent, bills, tenant agreements, notices, and apartment statements.",
    "Dispatch Coordinator": "Coordinates outgoing online orders, delivery handover, and route follow-up.",
    "Delivery Rider": "Handles customer delivery movement and proof of handover.",
    "Kitchen Staff": "Supports food preparation, food sales, and kitchen order fulfillment.",
    "Finance Officer": "Controls cashbook, expenses, payroll support, reconciliations, and reporting.",
    "Finance, HR & Payroll Officer": "Handles finance records, payroll support, attendance-linked administration, and staff documentation.",
    "CRM & Marketing Officer": "Grows repeat sales through customer follow-up, promotions, and campaigns.",
    "CRM, Marketing & Support Officer": "Runs customer follow-up and promotions while supporting shared operational tasks.",
    "HR & Payroll Officer": "Supports attendance, salaries, vacancies, staff records, and training.",
    "Support Staff": "General support role for shared tasks across the workspace.",
}
JOB_EMPLOYMENT_TYPES = [
    ("Full-Time", "Full-Time"),
    ("Part-Time", "Part-Time"),
    ("Contract", "Contract"),
    ("Temporary", "Temporary"),
    ("Internship", "Internship"),
    ("National Service", "National Service"),
]
JOB_VACANCY_STATUSES = [
    ("Draft", "Draft"),
    ("Open", "Open"),
    ("Shortlisting", "Shortlisting"),
    ("Interviewing", "Interviewing"),
    ("Offer Extended", "Offer Extended"),
    ("Filled", "Filled"),
    ("Closed", "Closed"),
]
SHIFT_TYPES = [
    ("Morning", "Morning"),
    ("Afternoon", "Afternoon"),
    ("Evening", "Evening"),
    ("Full Day", "Full Day"),
    ("Night", "Night"),
    ("Split", "Split"),
    ("On Call", "On Call"),
]
ATTENDANCE_STATUSES = [
    ("Scheduled", "Scheduled"),
    ("Present", "Present"),
    ("Late", "Late"),
    ("Absent", "Absent"),
    ("Checked Out", "Checked Out"),
    ("Off Duty", "Off Duty"),
]
APPROVAL_STATUSES = [
    ("Draft", "Draft"),
    ("Submitted", "Submitted"),
    ("Approved", "Approved"),
    ("Rejected", "Rejected"),
]
ASSET_CATEGORIES = [
    ("Equipment", "Equipment"),
    ("Appliance", "Appliance"),
    ("Furniture", "Furniture"),
    ("Electronics", "Electronics"),
    ("Tool", "Tool"),
    ("Vehicle / Transport", "Vehicle / Transport"),
    ("Property Fixture", "Property Fixture"),
    ("Other / Custom", "Other / Custom"),
]
ASSET_CONDITIONS = [("Excellent", "Excellent"), ("Good", "Good"), ("Fair", "Fair"), ("Poor", "Poor")]
ASSET_STATUSES = [
    ("In Use", "In Use"),
    ("In Storage", "In Storage"),
    ("Under Repair", "Under Repair"),
    ("Retired", "Retired"),
    ("Sold", "Sold"),
]
DEPRECIATION_METHODS = [
    ("Straight Line", "Straight Line"),
    ("Reducing Balance", "Reducing Balance"),
]
RECURRING_MODULE_TYPES = [
    ("expense", "Expense"),
    ("supplier-bill", "Supplier Bill"),
    ("maintenance-task", "Maintenance Task"),
    ("apartment-bill", "Apartment Bill"),
]
RECURRING_FREQUENCIES = [
    ("monthly", "Monthly"),
    ("quarterly", "Quarterly"),
    ("half-yearly", "Half-Yearly"),
    ("yearly", "Yearly"),
]
ACTIVE_STATES = [("active", "Active"), ("paused", "Paused")]
MAINTENANCE_PRIORITIES = [("Low", "Low"), ("Medium", "Medium"), ("High", "High"), ("Critical", "Critical")]
MAINTENANCE_STATUSES = [
    ("Open", "Open"),
    ("Scheduled", "Scheduled"),
    ("In Progress", "In Progress"),
    ("Completed", "Completed"),
]
WORK_ORDER_TYPES = [
    ("Preventive", "Preventive"),
    ("Corrective", "Corrective"),
    ("Inspection", "Inspection"),
    ("Emergency", "Emergency"),
    ("Installation", "Installation"),
]
MAINTENANCE_REQUEST_SOURCES = [
    ("Tenant", "Tenant"),
    ("Staff", "Staff"),
    ("Inspection", "Inspection"),
    ("System Reminder", "System Reminder"),
    ("Customer", "Customer"),
]
PLANNING_TYPES = [
    ("Area Target", "Area Target"),
    ("Budget Line", "Budget Line"),
    ("Marketing Push", "Marketing Push"),
    ("Operations Plan", "Operations Plan"),
]
CUSTOMER_SEGMENTS = [
    ("Lead", "Lead"),
    ("Walk-in", "Walk-in"),
    ("Repeat", "Repeat"),
    ("VIP", "VIP"),
    ("Apartment Tenant", "Apartment Tenant"),
    ("Community Account", "Community Account"),
    ("Dormant", "Dormant"),
]
CUSTOMER_STATUSES = [
    ("Active", "Active"),
    ("Follow Up", "Follow Up"),
    ("Do Not Disturb", "Do Not Disturb"),
    ("Inactive", "Inactive"),
]
LEAD_SOURCES = [
    ("Website", "Website"),
    ("POS", "POS"),
    ("Online Order", "Online Order"),
    ("Laundry", "Laundry"),
    ("Equipment Rental", "Equipment Rental"),
    ("WhatsApp", "WhatsApp"),
    ("Referral", "Referral"),
    ("Walk-in", "Walk-in"),
    ("Apartment", "Apartment"),
    ("Social Media", "Social Media"),
    ("Flyer", "Flyer"),
]
CONTACT_PREFERENCES = [("WhatsApp", "WhatsApp"), ("Call", "Call"), ("SMS", "SMS"), ("Email", "Email")]
PROMOTION_TYPES = [
    ("Discount", "Discount"),
    ("Bundle", "Bundle"),
    ("Referral", "Referral"),
    ("Free Delivery", "Free Delivery"),
    ("Loyalty Reward", "Loyalty Reward"),
    ("Seasonal Offer", "Seasonal Offer"),
]
PROMOTION_STATUSES = [
    ("Draft", "Draft"),
    ("Scheduled", "Scheduled"),
    ("Running", "Running"),
    ("Paused", "Paused"),
    ("Ended", "Ended"),
]
CAMPAIGN_CHANNELS = [
    ("WhatsApp", "WhatsApp"),
    ("SMS", "SMS"),
    ("Phone Follow-Up", "Phone Follow-Up"),
    ("Social Media", "Social Media"),
    ("Flyers", "Flyers"),
]
CAMPAIGN_GOALS = [
    ("Promo Push", "Promo Push"),
    ("Repeat Sales", "Repeat Sales"),
    ("New Leads", "New Leads"),
    ("Collection Follow-Up", "Collection Follow-Up"),
    ("Order Recovery", "Order Recovery"),
]
CAMPAIGN_STATUSES = [("Draft", "Draft"), ("Ready", "Ready"), ("Sent", "Sent"), ("Closed", "Closed")]
DISPATCH_TYPES = [
    ("Online Order", "Online Order"),
    ("Laundry Pickup", "Laundry Pickup"),
    ("Laundry Dropoff", "Laundry Dropoff"),
    ("Water Delivery", "Water Delivery"),
    ("Kitchen Delivery", "Kitchen Delivery"),
    ("Equipment Dropoff", "Equipment Dropoff"),
]
DISPATCH_STATUSES = [
    ("Pending", "Pending"),
    ("Packed", "Packed"),
    ("Out For Delivery", "Out For Delivery"),
    ("Delivered", "Delivered"),
    ("Failed", "Failed"),
    ("Cancelled", "Cancelled"),
]
DISPATCH_PAYMENT_STATUSES = [
    ("Pending", "Pending"),
    ("Part Paid", "Part Paid"),
    ("Paid", "Paid"),
    ("Cash On Delivery", "Cash On Delivery"),
    ("Refunded", "Refunded"),
]
KNOWLEDGE_ENTRY_TYPES = [
    ("SOP", "SOP"),
    ("Policy", "Policy"),
    ("Training", "Training"),
    ("Checklist", "Checklist"),
    ("FAQ", "FAQ"),
    ("Template", "Template"),
    ("Incident Playbook", "Incident Playbook"),
]
KNOWLEDGE_DELIVERY_MODES = [
    ("Document", "Document"),
    ("Video", "Video"),
    ("Demo", "Demo"),
    ("Shadowing", "Shadowing"),
    ("Quiz", "Quiz"),
    ("Workshop", "Workshop"),
]
KNOWLEDGE_STATUSES = [
    ("Draft", "Draft"),
    ("Active", "Active"),
    ("Training Due", "Training Due"),
    ("Completed", "Completed"),
    ("Under Review", "Under Review"),
    ("Archived", "Archived"),
]
KNOWLEDGE_AUDIENCE_OPTIONS = [
    ("All Staff", "All Staff"),
    *STAFF_WORK_ROLES,
]


@dataclass(slots=True)
class FieldDefinition:
    name: str
    label: str
    field_type: str = "text"
    required: bool = False
    options: list[tuple[str, str]] = field(default_factory=list)
    placeholder: str = ""
    step: str = "0.01"
    rows: int = 4


@dataclass(slots=True)
class ModuleDefinition:
    key: str
    label: str
    legacy_collection: str
    menu_group: str
    amount_field: str = ""
    date_field: str = ""
    month_field: str = ""
    title_field: str = ""
    status_field: str = ""
    fields: list[FieldDefinition] = field(default_factory=list)
    editable: bool = True


MODULES: dict[str, ModuleDefinition] = {
    "expenses": ModuleDefinition(
        key="expenses",
        label="Expenses",
        legacy_collection="expenses",
        menu_group="Finance",
        amount_field="amount",
        date_field="date",
        title_field="vendor",
        status_field="receiptStatus",
        fields=[
            FieldDefinition("businessAreaId", "Business Area", "select", True, BUSINESS_AREA_OPTIONS),
            FieldDefinition("date", "Date", "date", True),
            FieldDefinition("vendor", "Vendor", "text", True),
            FieldDefinition("category", "Category", "text", True),
            FieldDefinition("description", "Description", "textarea"),
            FieldDefinition("paymentMethod", "Payment Method", "select", True, [(m, m) for m in PAYMENT_METHODS]),
            FieldDefinition("receiptStatus", "Receipt Status", "select", True, [(m, m) for m in RECEIPT_STATUSES]),
            FieldDefinition("amount", "Amount", "number", True),
            FieldDefinition("notes", "Notes", "textarea"),
        ],
    ),
    "budgets": ModuleDefinition(
        key="budgets",
        label="Budget Planner (Legacy)",
        legacy_collection="budgets",
        menu_group="Finance",
        amount_field="budgetAmount",
        month_field="month",
        title_field="category",
        fields=[
            FieldDefinition("month", "Month", "month", True),
            FieldDefinition("businessAreaId", "Business Area", "select", True, BUSINESS_AREA_OPTIONS),
            FieldDefinition("category", "Category", "text", True),
            FieldDefinition("budgetAmount", "Budget Amount", "number", True),
            FieldDefinition("notes", "Notes", "textarea"),
        ],
    ),
    "sales": ModuleDefinition(
        key="sales",
        label="Daily Sales",
        legacy_collection="sales",
        menu_group="Finance",
        amount_field="amount",
        date_field="date",
        title_field="sourceLabel",
        status_field="sourceType",
        fields=[
            FieldDefinition("businessAreaId", "Business Area", "select", True, BUSINESS_AREA_OPTIONS),
            FieldDefinition("date", "Sales Date", "date", True),
            FieldDefinition("amount", "Amount", "number", True),
            FieldDefinition("costAmount", "Cost Amount", "number"),
            FieldDefinition("profitAmount", "Profit", "number"),
            FieldDefinition("sourceType", "Source Type", "text"),
            FieldDefinition("sourceLabel", "Source Label", "text"),
            FieldDefinition("notes", "Notes", "textarea"),
        ],
    ),
    "apartments": ModuleDefinition(
        key="apartments",
        label="Apartment Rentals",
        legacy_collection="rentals",
        menu_group="Property",
        amount_field="rentPaid",
        month_field="month",
        title_field="tenantName",
        status_field="occupancyStatus",
        fields=[
            FieldDefinition("month", "Month", "month", True),
            FieldDefinition("suite", "Suite", "select", True, [(name, name) for name in SUITE_NAMES]),
            FieldDefinition("occupancyStatus", "Occupancy", "select", True, [(x, x) for x in OCCUPANCY_STATUSES]),
            FieldDefinition("tenantName", "Tenant Name", "text"),
            FieldDefinition("tenantPhone", "Tenant Phone", "text"),
            FieldDefinition("tenantEmail", "Tenant Email", "text"),
            FieldDefinition("tenantAddress", "Tenant Address", "text"),
            FieldDefinition("tenantIdNumber", "Tenant ID / Ghana Card", "text"),
            FieldDefinition("emergencyContactName", "Emergency Contact Name", "text"),
            FieldDefinition("emergencyContactPhone", "Emergency Contact Phone", "text"),
            FieldDefinition("guarantorName", "Guarantor Name", "text"),
            FieldDefinition("guarantorPhone", "Guarantor Phone", "text"),
            FieldDefinition("occupantsCount", "Occupants Count", "number", False, step="1"),
            FieldDefinition("moveInDate", "Move-In Date", "date"),
            FieldDefinition("noticeDate", "Notice Date", "date"),
            FieldDefinition("moveOutDate", "Move-Out Date", "date"),
            FieldDefinition("leaseStartDate", "Lease Start Date", "date"),
            FieldDefinition("leaseEndDate", "Lease End Date", "date"),
            FieldDefinition("rentCycleType", "Rent Cycle", "select", True, RENT_CYCLES),
            FieldDefinition("rentCycleMonths", "Custom Cycle Months", "number", False, step="1"),
            FieldDefinition("rentCycleAmount", "Rent Cycle Amount", "number"),
            FieldDefinition("rentDue", "Rent Due", "number"),
            FieldDefinition("rentPaid", "Rent Paid", "number"),
            FieldDefinition("bedRentDue", "Bed Rent Due", "number"),
            FieldDefinition("bedRentPaid", "Bed Rent Paid", "number"),
            FieldDefinition("mattressRentDue", "Mattress Rent Due", "number"),
            FieldDefinition("mattressRentPaid", "Mattress Rent Paid", "number"),
            FieldDefinition("rentPaymentDate", "Rent Payment Date", "date"),
            FieldDefinition("rentPaymentMethod", "Rent Payment Method", "select", False, [(m, m) for m in PAYMENT_METHODS]),
            FieldDefinition("rentPaymentReference", "Rent Payment Reference", "text"),
            FieldDefinition("rentReceivedBy", "Rent Received By", "text"),
            FieldDefinition("rentCoverageStartDate", "Coverage Start", "date"),
            FieldDefinition("rentCoverageEndDate", "Coverage End", "date"),
            FieldDefinition("nextRentDueDate", "Next Rent Due", "date"),
            FieldDefinition("creditBroughtForward", "Credit / Advance B/F", "number"),
            FieldDefinition("waterBill", "Water Bill", "number"),
            FieldDefinition("toiletBill", "Toilet Bill", "number"),
            FieldDefinition("sweepingBill", "Sweeping / Gutter", "number"),
            FieldDefinition("wasteBill", "Waste Bill", "number"),
            FieldDefinition("customChargeLabel", "Custom Charge Label", "text"),
            FieldDefinition("customChargeAmount", "Custom Charge Amount", "number"),
            FieldDefinition("customChargeTwoLabel", "Second Custom Charge Label", "text"),
            FieldDefinition("customChargeTwoAmount", "Second Custom Charge Amount", "number"),
            FieldDefinition("billDueDate", "Bills Due Date", "date"),
            FieldDefinition("billAmountPaid", "Bills Paid", "number"),
            FieldDefinition("billPaymentDate", "Bills Payment Date", "date"),
            FieldDefinition("billPaymentMethod", "Bills Payment Method", "select", False, [(m, m) for m in PAYMENT_METHODS]),
            FieldDefinition("billPaymentReference", "Bills Payment Reference", "text"),
            FieldDefinition("billReceivedBy", "Bills Received By", "text"),
            FieldDefinition("arrearsBroughtForward", "Arrears B/F", "number"),
            FieldDefinition("lateFee", "Late Fee", "number"),
            FieldDefinition("securityDepositHeld", "Security Deposit Held", "number"),
            FieldDefinition("nextInspectionDate", "Next Inspection Date", "date"),
            FieldDefinition("rentReviewDate", "Rent Review Date", "date"),
            FieldDefinition("renewalDate", "Renewal Date", "date"),
            FieldDefinition("renewalStatus", "Renewal Status", "select", False, RENEWAL_STATUSES),
            FieldDefinition("notes", "Notes", "textarea"),
        ],
    ),
    "petty_cash": ModuleDefinition(
        key="petty_cash",
        label="Petty Cash",
        legacy_collection="pettyCash",
        menu_group="Finance",
        amount_field="amount",
        date_field="date",
        title_field="description",
        status_field="transactionTypeId",
        fields=[
            FieldDefinition("date", "Date", "date", True),
            FieldDefinition("businessAreaId", "Business Area", "select", True, BUSINESS_AREA_OPTIONS),
            FieldDefinition("transactionTypeId", "Transaction Type", "select", True, PETTY_CASH_TRANSACTION_TYPES),
            FieldDefinition("description", "Description", "text", True),
            FieldDefinition("amount", "Amount", "number", True),
            FieldDefinition("paymentMethod", "Payment Method", "select", False, [(m, m) for m in PAYMENT_METHODS]),
            FieldDefinition("notes", "Notes", "textarea"),
        ],
    ),
    "petty_cash_budgets": ModuleDefinition(
        key="petty_cash_budgets",
        label="Petty Cash Budgets",
        legacy_collection="pettyCashBudgets",
        menu_group="Finance",
        amount_field="budgetAmount",
        month_field="month",
        title_field="businessAreaId",
        fields=[
            FieldDefinition("month", "Month", "month", True),
            FieldDefinition("businessAreaId", "Business Area", "select", True, BUSINESS_AREA_OPTIONS),
            FieldDefinition("budgetAmount", "Budget Amount", "number", True),
            FieldDefinition("notes", "Notes", "textarea"),
        ],
    ),
    "salary_records": ModuleDefinition(
        key="salary_records",
        label="Payroll & Payslips",
        legacy_collection="salaryRecords",
        menu_group="People",
        amount_field="grossPay",
        month_field="month",
        title_field="staffName",
        status_field="status",
        fields=[
            FieldDefinition("month", "Month", "month", True),
            FieldDefinition("staffName", "Staff Name", "text", True),
            FieldDefinition("staffRole", "Staff Role", "select", False, STAFF_WORK_ROLES),
            FieldDefinition("businessAreaId", "Business Area", "select", False, BUSINESS_AREA_OPTIONS),
            FieldDefinition("payFrequency", "Pay Frequency", "select", False, SALARY_FREQUENCIES),
            FieldDefinition("payPeriodStart", "Pay Period Start", "date"),
            FieldDefinition("payPeriodEnd", "Pay Period End", "date"),
            FieldDefinition("baseSalary", "Base Salary", "number"),
            FieldDefinition("allowance", "Allowance", "number"),
            FieldDefinition("overtimeHours", "Overtime Hours", "number"),
            FieldDefinition("overtimeRate", "Overtime Hourly Rate", "number"),
            FieldDefinition("overtimePay", "Overtime Pay", "number"),
            FieldDefinition("bonus", "Bonus", "number"),
            FieldDefinition("grossPay", "Gross Pay", "number"),
            FieldDefinition("taxAmount", "Tax / PAYE", "number"),
            FieldDefinition("ssnitAmount", "SSNIT", "number"),
            FieldDefinition("loanDeduction", "Loan Deduction", "number"),
            FieldDefinition("deductions", "Other Deductions", "number"),
            FieldDefinition("totalDeductions", "Total Deductions", "number"),
            FieldDefinition("netPay", "Net Pay", "number"),
            FieldDefinition("amountPaid", "Amount Paid", "number"),
            FieldDefinition("balanceDue", "Balance Due", "number"),
            FieldDefinition("paymentDate", "Payment Date", "date"),
            FieldDefinition("paymentMethod", "Payment Method", "select", False, [(m, m) for m in PAYMENT_METHODS]),
            FieldDefinition("paymentReference", "Payment Reference", "text"),
            FieldDefinition("status", "Status", "select", False, SALARY_PAYMENT_STATUSES),
            FieldDefinition("notes", "Notes", "textarea"),
        ],
    ),
    "cashbook_entries": ModuleDefinition(
        key="cashbook_entries",
        label="Cashbook / Bankbook",
        legacy_collection="cashbookEntries",
        menu_group="Finance",
        amount_field="amount",
        date_field="date",
        title_field="accountName",
        status_field="entryType",
        fields=[
            FieldDefinition("date", "Date", "date", True),
            FieldDefinition("accountName", "Account", "text", True),
            FieldDefinition("entryType", "Entry Type", "select", True, CASHBOOK_ENTRY_TYPES),
            FieldDefinition("amount", "Amount", "number", True),
            FieldDefinition("paymentMethod", "Payment Method", "select", False, [(m, m) for m in PAYMENT_METHODS]),
            FieldDefinition("reference", "Reference", "text"),
            FieldDefinition("notes", "Notes", "textarea"),
        ],
    ),
    "laundry_tickets": ModuleDefinition(
        key="laundry_tickets",
        label="Laundry Job Tickets",
        legacy_collection="laundryTickets",
        menu_group="Services",
        amount_field="amountDue",
        date_field="ticketDate",
        title_field="customerName",
        status_field="status",
        fields=[
            FieldDefinition("ticketDate", "Ticket Date", "date", True),
            FieldDefinition("businessAreaId", "Business Area", "select", True, BUSINESS_AREA_OPTIONS),
            FieldDefinition("customerName", "Customer Name", "text", True),
            FieldDefinition("customerPhone", "Customer Phone", "text"),
            FieldDefinition("serviceType", "Service Type", "select", True, LAUNDRY_SERVICE_TYPES),
            FieldDefinition("serviceCategory", "Laundry Category", "select", False, LAUNDRY_ITEM_CATEGORY_OPTIONS),
            FieldDefinition("laundryItem", "Laundry Item", "text", True),
            FieldDefinition("itemSummary", "Additional Details", "textarea"),
            FieldDefinition("pieces", "Pieces", "number", False, step="1"),
            FieldDefinition("amountDue", "Amount Due", "number", True),
            FieldDefinition("costAmount", "Service Cost", "number"),
            FieldDefinition("amountPaid", "Amount Paid", "number"),
            FieldDefinition("paymentDate", "Payment Date", "date"),
            FieldDefinition("paymentMethod", "Payment Method", "select", False, [(m, m) for m in PAYMENT_METHODS]),
            FieldDefinition("paymentReference", "Payment Reference", "text"),
            FieldDefinition("dueDate", "Due Date", "date"),
            FieldDefinition("readyDate", "Ready Date", "date"),
            FieldDefinition("deliveryMode", "Delivery Mode", "select", False, [(item, item) for item in LAUNDRY_DELIVERY_MODES]),
            FieldDefinition("status", "Status", "select", True, [(item, item) for item in LAUNDRY_STATUSES]),
            FieldDefinition("notes", "Notes", "textarea"),
        ],
    ),
    "equipment_rental_bookings": ModuleDefinition(
        key="equipment_rental_bookings",
        label="Equipment Rentals",
        legacy_collection="equipmentRentalBookings",
        menu_group="Services",
        amount_field="rentalFee",
        date_field="bookingDate",
        title_field="equipmentItem",
        status_field="status",
        fields=[
            FieldDefinition("bookingDate", "Booking Date", "date", True),
            FieldDefinition("businessAreaId", "Business Area", "select", True, BUSINESS_AREA_OPTIONS),
            FieldDefinition("equipmentCategory", "Rental Category", "select", False, EQUIPMENT_RENTAL_CATEGORY_OPTIONS),
            FieldDefinition("equipmentItem", "Equipment Item", "text", True),
            FieldDefinition("customerName", "Customer Name", "text", True),
            FieldDefinition("customerPhone", "Customer Phone", "text"),
            FieldDefinition("rentalDays", "Rental Days", "number", False, step="1"),
            FieldDefinition("rentalFee", "Rental Fee", "number", True),
            FieldDefinition("costAmount", "Service Cost", "number"),
            FieldDefinition("amountPaid", "Amount Paid", "number"),
            FieldDefinition("paymentDate", "Payment Date", "date"),
            FieldDefinition("paymentMethod", "Payment Method", "select", False, [(m, m) for m in PAYMENT_METHODS]),
            FieldDefinition("paymentReference", "Payment Reference", "text"),
            FieldDefinition("depositAmount", "Deposit Held", "number"),
            FieldDefinition("damageCharge", "Damage Charge", "number"),
            FieldDefinition("outDate", "Out Date", "date"),
            FieldDefinition("dueDate", "Due Date", "date"),
            FieldDefinition("returnDate", "Return Date", "date"),
            FieldDefinition("status", "Status", "select", True, [(item, item) for item in EQUIPMENT_RENTAL_STATUSES]),
            FieldDefinition("conditionOut", "Condition Out", "select", False, [(item, item) for item in EQUIPMENT_CONDITIONS]),
            FieldDefinition("conditionIn", "Condition In", "select", False, [(item, item) for item in EQUIPMENT_CONDITIONS]),
            FieldDefinition("reference", "Reference", "text"),
            FieldDefinition("notes", "Notes", "textarea"),
        ],
    ),
    "security_deposit_records": ModuleDefinition(
        key="security_deposit_records",
        label="Deposits & Tenant Charges",
        legacy_collection="securityDepositRecords",
        menu_group="Property",
        amount_field="depositPaid",
        date_field="captureDate",
        title_field="tenantName",
        status_field="status",
        fields=[
            FieldDefinition("captureDate", "Capture Date", "date", True),
            FieldDefinition("suite", "Suite", "select", True, [(name, name) for name in SUITE_NAMES]),
            FieldDefinition("tenantName", "Tenant Name", "text", True),
            FieldDefinition("tenantPhone", "Tenant Phone", "text"),
            FieldDefinition("depositExpected", "Deposit Expected", "number"),
            FieldDefinition("depositPaid", "Deposit Paid", "number"),
            FieldDefinition("depositPaymentDate", "Deposit Payment Date", "date"),
            FieldDefinition("chargesRaised", "Tenant Charges Raised", "number"),
            FieldDefinition("chargesPaid", "Tenant Charges Paid", "number"),
            FieldDefinition("chargePaymentDate", "Charge Payment Date", "date"),
            FieldDefinition("deductionFromDeposit", "Deduction From Deposit", "number"),
            FieldDefinition("refundDue", "Refund Due", "number"),
            FieldDefinition("refundPaid", "Refund Paid", "number"),
            FieldDefinition("refundPaymentDate", "Refund Payment Date", "date"),
            FieldDefinition("depositDueDate", "Deposit Due Date", "date"),
            FieldDefinition("refundDueDate", "Refund Due Date", "date"),
            FieldDefinition(
                "status",
                "Status",
                "select",
                True,
                [
                    ("Active Hold", "Active Hold"),
                    ("Part Paid", "Part Paid"),
                    ("Charge Follow-up", "Charge Follow-up"),
                    ("Refund Pending", "Refund Pending"),
                    ("Closed", "Closed"),
                ],
            ),
            FieldDefinition("notes", "Notes", "textarea"),
        ],
    ),
    "ledger_entries": ModuleDefinition(
        key="ledger_entries",
        label="Ledgers",
        legacy_collection="ledgerEntries",
        menu_group="Finance",
        amount_field="amount",
        date_field="entryDate",
        title_field="partyName",
        status_field="entryType",
        fields=[
            FieldDefinition("entryDate", "Entry Date", "date", True),
            FieldDefinition("businessAreaId", "Business Area", "select", True, BUSINESS_AREA_OPTIONS),
            FieldDefinition("partyType", "Party Type", "select", True, LEDGER_PARTY_TYPES),
            FieldDefinition("partyName", "Party Name", "text", True),
            FieldDefinition("partyPhone", "Party Phone", "text"),
            FieldDefinition("suite", "Suite / Reference", "text"),
            FieldDefinition("entryType", "Entry Type", "select", True, LEDGER_ENTRY_TYPES),
            FieldDefinition("amount", "Amount", "number", True),
            FieldDefinition("dueDate", "Due Date", "date"),
            FieldDefinition("reference", "Reference", "text"),
            FieldDefinition("notes", "Notes", "textarea"),
        ],
    ),
    "mobile_money_reconciliations": ModuleDefinition(
        key="mobile_money_reconciliations",
        label="Mobile Money Reconciliation",
        legacy_collection="mobileMoneyReconciliations",
        menu_group="Finance",
        amount_field="closingCashCounted",
        date_field="date",
        title_field="provider",
        fields=[
            FieldDefinition("date", "Date", "date", True),
            FieldDefinition("provider", "Provider", "select", True, MOBILE_MONEY_PROVIDERS),
            FieldDefinition("openingCash", "Start Cash", "number", True),
            FieldDefinition("openingECash", "Start E-Cash", "number", True),
            FieldDefinition("cashTopUp", "Extra Physical Cash Added", "number"),
            FieldDefinition("cashTopUpSource", "Cash Top-Up From", "text"),
            FieldDefinition("eCashTopUp", "Extra E-Cash Added", "number"),
            FieldDefinition("eCashTopUpSource", "E-Cash Top-Up From", "text"),
            FieldDefinition("cashRemoved", "Physical Cash Moved Out", "number"),
            FieldDefinition("eCashRemoved", "E-Cash Moved Out", "number"),
            FieldDefinition("cashInValue", "Total Cash-In Value", "number"),
            FieldDefinition("cashOutValue", "Total Cash-Out Value", "number"),
            FieldDefinition("serviceFees", "Service Fees Earned", "number"),
            FieldDefinition("operatingExpense", "Operating Expense", "number"),
            FieldDefinition("closingCashCounted", "Physical Cash Left At Close", "number"),
            FieldDefinition("closingECashCounted", "E-Cash Left At Close", "number"),
            FieldDefinition("notes", "Notes", "textarea"),
        ],
    ),
    "mobile_money_transactions": ModuleDefinition(
        key="mobile_money_transactions",
        label="Mobile Money Sales",
        legacy_collection="mobileMoneyTransactions",
        menu_group="Finance",
        amount_field="salesAmount",
        date_field="date",
        title_field="customerName",
        status_field="status",
        fields=[
            FieldDefinition("date", "Date", "date", True),
            FieldDefinition("provider", "Provider", "select", True, MOBILE_MONEY_PROVIDERS),
            FieldDefinition("serviceType", "Service Type", "select", True, MOBILE_MONEY_SERVICE_TYPES),
            FieldDefinition("customerName", "Customer Name", "text"),
            FieldDefinition("customerPhone", "Customer Phone", "text"),
            FieldDefinition("momoNumber", "MoMo / SIM Number", "text"),
            FieldDefinition("transactionValue", "Transaction Value", "number"),
            FieldDefinition("salesAmount", "Fee Earned / Commission", "number", True),
            FieldDefinition("costAmount", "Direct Cost", "number"),
            FieldDefinition("floatImpact", "Float Impact", "select", False, MOBILE_MONEY_FLOAT_IMPACTS),
            FieldDefinition("reference", "Reference", "text"),
            FieldDefinition("status", "Status", "select", True, MOBILE_MONEY_TRANSACTION_STATUSES),
            FieldDefinition("notes", "Notes", "textarea"),
        ],
    ),
    "suppliers": ModuleDefinition(
        key="suppliers",
        label="Suppliers",
        legacy_collection="suppliers",
        menu_group="Procurement",
        amount_field="amountDue",
        date_field="invoiceDate",
        title_field="supplierName",
        fields=[
            FieldDefinition("invoiceDate", "Invoice Date", "date", True),
            FieldDefinition("businessAreaId", "Business Area", "select", True, BUSINESS_AREA_OPTIONS),
            FieldDefinition("supplierName", "Supplier Name", "text", True),
            FieldDefinition("category", "Expense Type", "text"),
            FieldDefinition("itemDescription", "Item / Description", "textarea"),
            FieldDefinition("invoiceReference", "Invoice Reference", "text"),
            FieldDefinition("amountDue", "Amount Due", "number", True),
            FieldDefinition("amountPaid", "Amount Paid", "number"),
            FieldDefinition("dueDate", "Due Date", "date"),
            FieldDefinition("paymentDate", "Payment Date", "date"),
            FieldDefinition("paymentMethod", "Payment Method", "select", False, [(m, m) for m in PAYMENT_METHODS]),
            FieldDefinition("notes", "Notes", "textarea"),
        ],
    ),
    "asset_records": ModuleDefinition(
        key="asset_records",
        label="Asset Register & Depreciation",
        legacy_collection="assetRecords",
        menu_group="Admin",
        amount_field="currentValue",
        date_field="acquiredDate",
        title_field="assetName",
        status_field="status",
        fields=[
            FieldDefinition("acquiredDate", "Acquired Date", "date", True),
            FieldDefinition("businessAreaId", "Business Area", "select", True, BUSINESS_AREA_OPTIONS),
            FieldDefinition("assetName", "Asset Name", "text", True),
            FieldDefinition("assetCode", "Asset Code", "text"),
            FieldDefinition("assetCategory", "Asset Category", "select", True, ASSET_CATEGORIES),
            FieldDefinition("location", "Location", "text"),
            FieldDefinition("supplierName", "Supplier Name", "text"),
            FieldDefinition("serialNumber", "Serial Number", "text"),
            FieldDefinition("purchaseCost", "Purchase Cost", "number", True),
            FieldDefinition("salvageValue", "Salvage Value", "number"),
            FieldDefinition("usefulLifeMonths", "Useful Life (Months)", "number", False, step="1"),
            FieldDefinition("depreciationMethod", "Depreciation Method", "select", False, DEPRECIATION_METHODS),
            FieldDefinition("monthlyDepreciation", "Monthly Depreciation", "number"),
            FieldDefinition("annualDepreciation", "Annual Depreciation", "number"),
            FieldDefinition("accumulatedDepreciation", "Accumulated Depreciation", "number"),
            FieldDefinition("currentValue", "Current Value", "number"),
            FieldDefinition("condition", "Condition", "select", True, ASSET_CONDITIONS),
            FieldDefinition("status", "Status", "select", True, ASSET_STATUSES),
            FieldDefinition("assignedTo", "Assigned To", "text"),
            FieldDefinition("lastServiceDate", "Last Service Date", "date"),
            FieldDefinition("nextServiceDate", "Next Service Date", "date"),
            FieldDefinition("warrantyEndDate", "Warranty End Date", "date"),
            FieldDefinition("replacementDueDate", "Replacement Due Date", "date"),
            FieldDefinition("notes", "Notes", "textarea"),
        ],
    ),
    "forecast_plans": ModuleDefinition(
        key="forecast_plans",
        label="Planning & Targets",
        legacy_collection="forecastPlans",
        menu_group="Planning",
        amount_field="totalBudget",
        month_field="month",
        title_field="planName",
        status_field="planType",
        fields=[
            FieldDefinition("month", "Planning Month", "month", True),
            FieldDefinition("businessAreaId", "Business Area", "select", True, BUSINESS_AREA_OPTIONS),
            FieldDefinition("planType", "Plan Type", "select", True, PLANNING_TYPES),
            FieldDefinition("planName", "Plan Name", "text", True),
            FieldDefinition("category", "Category", "text"),
            FieldDefinition("revenueTarget", "Revenue Target", "number"),
            FieldDefinition("budgetAmount", "Budget Line Amount", "number"),
            FieldDefinition("expenseBudget", "Expense Budget", "number"),
            FieldDefinition("salaryBudget", "Salary Budget", "number"),
            FieldDefinition("marketingBudget", "Marketing Budget", "number"),
            FieldDefinition("pettyCashBudget", "Petty Cash Budget", "number"),
            FieldDefinition("stockBudget", "Stock Budget", "number"),
            FieldDefinition("totalBudget", "Total Budget", "number"),
            FieldDefinition("notes", "Notes", "textarea"),
        ],
    ),
    "customer_crm": ModuleDefinition(
        key="customer_crm",
        label="Customer CRM",
        legacy_collection="customerCrm",
        menu_group="Growth",
        amount_field="lifetimeValue",
        date_field="captureDate",
        title_field="customerName",
        status_field="status",
        fields=[
            FieldDefinition("captureDate", "Capture Date", "date", True),
            FieldDefinition("businessAreaId", "Business Area", "select", True, BUSINESS_AREA_OPTIONS),
            FieldDefinition("customerName", "Customer Name", "text", True),
            FieldDefinition("customerPhone", "Customer Phone", "text"),
            FieldDefinition("customerEmail", "Customer Email", "text"),
            FieldDefinition("customerSegment", "Customer Segment", "select", False, CUSTOMER_SEGMENTS),
            FieldDefinition("leadSource", "Lead Source", "select", False, LEAD_SOURCES),
            FieldDefinition("preferredContact", "Preferred Contact", "select", False, CONTACT_PREFERENCES),
            FieldDefinition("lastOrderDate", "Last Order Date", "date"),
            FieldDefinition("followUpDate", "Follow-Up Date", "date"),
            FieldDefinition("lifetimeValue", "Lifetime Value", "number"),
            FieldDefinition("status", "Status", "select", True, CUSTOMER_STATUSES),
            FieldDefinition("notes", "Notes", "textarea"),
        ],
    ),
    "promotions": ModuleDefinition(
        key="promotions",
        label="Promotions",
        legacy_collection="promotions",
        menu_group="Growth",
        amount_field="expectedRevenue",
        date_field="startDate",
        title_field="campaignName",
        status_field="status",
        fields=[
            FieldDefinition("campaignName", "Campaign Name", "text", True),
            FieldDefinition("businessAreaId", "Business Area", "select", True, BUSINESS_AREA_OPTIONS),
            FieldDefinition("promotionType", "Promotion Type", "select", True, PROMOTION_TYPES),
            FieldDefinition("offerCode", "Offer Code", "text"),
            FieldDefinition("targetSegment", "Target Segment", "select", False, CUSTOMER_SEGMENTS),
            FieldDefinition("startDate", "Start Date", "date", True),
            FieldDefinition("endDate", "End Date", "date"),
            FieldDefinition("discountValue", "Discount / Offer Value", "number"),
            FieldDefinition("budgetAmount", "Promo Budget", "number"),
            FieldDefinition("expectedRevenue", "Expected Revenue", "number"),
            FieldDefinition("status", "Status", "select", True, PROMOTION_STATUSES),
            FieldDefinition("notes", "Notes", "textarea"),
        ],
    ),
    "whatsapp_campaigns": ModuleDefinition(
        key="whatsapp_campaigns",
        label="WhatsApp Campaign Center",
        legacy_collection="whatsappCampaigns",
        menu_group="Growth",
        amount_field="revenueGenerated",
        date_field="campaignDate",
        title_field="campaignName",
        status_field="status",
        fields=[
            FieldDefinition("campaignDate", "Campaign Date", "date", True),
            FieldDefinition("businessAreaId", "Business Area", "select", True, BUSINESS_AREA_OPTIONS),
            FieldDefinition("campaignName", "Campaign Name", "text", True),
            FieldDefinition("channelType", "Channel", "select", True, CAMPAIGN_CHANNELS),
            FieldDefinition("audienceSegment", "Audience Segment", "select", False, CUSTOMER_SEGMENTS),
            FieldDefinition("messageGoal", "Message Goal", "select", True, CAMPAIGN_GOALS),
            FieldDefinition("sentCount", "Messages Sent", "number"),
            FieldDefinition("responseCount", "Responses", "number"),
            FieldDefinition("orderCount", "Orders Won", "number"),
            FieldDefinition("revenueGenerated", "Revenue Generated", "number"),
            FieldDefinition("responseRate", "Response Rate %", "number"),
            FieldDefinition("conversionRate", "Conversion Rate %", "number"),
            FieldDefinition("status", "Status", "select", True, CAMPAIGN_STATUSES),
            FieldDefinition("followUpDate", "Next Follow-Up Date", "date"),
            FieldDefinition("notes", "Notes", "textarea"),
        ],
    ),
    "campaign_roi": ModuleDefinition(
        key="campaign_roi",
        label="Campaign ROI",
        legacy_collection="campaignRoi",
        menu_group="Growth",
        amount_field="roiAmount",
        month_field="month",
        title_field="campaignName",
        fields=[
            FieldDefinition("month", "Report Month", "month", True),
            FieldDefinition("businessAreaId", "Business Area", "select", True, BUSINESS_AREA_OPTIONS),
            FieldDefinition("campaignName", "Campaign Name", "text", True),
            FieldDefinition("channelType", "Channel", "select", True, CAMPAIGN_CHANNELS),
            FieldDefinition("amountSpent", "Campaign Spend", "number"),
            FieldDefinition("leadsCount", "Leads", "number", False, step="1"),
            FieldDefinition("conversionsCount", "Conversions", "number", False, step="1"),
            FieldDefinition("revenueGenerated", "Revenue Generated", "number"),
            FieldDefinition("roiAmount", "ROI Amount", "number"),
            FieldDefinition("roiPercent", "ROI %", "number"),
            FieldDefinition("notes", "Notes", "textarea"),
        ],
    ),
    "delivery_dispatch": ModuleDefinition(
        key="delivery_dispatch",
        label="Delivery / Dispatch",
        legacy_collection="deliveryDispatch",
        menu_group="Delivery",
        amount_field="cashCollected",
        date_field="dispatchDate",
        title_field="orderReference",
        status_field="dispatchStatus",
        fields=[
            FieldDefinition("dispatchDate", "Dispatch Date", "date", True),
            FieldDefinition("businessAreaId", "Business Area", "select", True, BUSINESS_AREA_OPTIONS),
            FieldDefinition("dispatchType", "Dispatch Type", "select", True, DISPATCH_TYPES),
            FieldDefinition("orderReference", "Order / Ticket Reference", "text", True),
            FieldDefinition("customerName", "Customer Name", "text", True),
            FieldDefinition("customerPhone", "Customer Phone", "text"),
            FieldDefinition("deliveryAddress", "Delivery Address", "textarea"),
            FieldDefinition("riderName", "Rider / Dispatcher", "text"),
            FieldDefinition("dispatchStatus", "Dispatch Status", "select", True, DISPATCH_STATUSES),
            FieldDefinition("paymentStatus", "Payment Status", "select", False, DISPATCH_PAYMENT_STATUSES),
            FieldDefinition("orderTotal", "Order Total", "number"),
            FieldDefinition("cashCollected", "Cash Collected", "number"),
            FieldDefinition("deliveryFee", "Delivery Fee", "number"),
            FieldDefinition("riderCost", "Rider Cost", "number"),
            FieldDefinition("deliveryMargin", "Delivery Margin", "number"),
            FieldDefinition("outstandingAmount", "Outstanding Amount", "number"),
            FieldDefinition("expectedDeliveryDate", "Expected Delivery Date", "date"),
            FieldDefinition("deliveredDate", "Delivered Date", "date"),
            FieldDefinition("notes", "Notes", "textarea"),
        ],
    ),
    "recurring_controls": ModuleDefinition(
        key="recurring_controls",
        label="Reminder Center",
        legacy_collection="recurringControls",
        menu_group="Admin",
        amount_field="amount",
        date_field="nextDueDate",
        title_field="title",
        status_field="activeState",
        fields=[
            FieldDefinition("title", "Control Name", "text", True),
            FieldDefinition("moduleType", "Module", "select", True, RECURRING_MODULE_TYPES),
            FieldDefinition("businessAreaId", "Business Area", "select", True, BUSINESS_AREA_OPTIONS),
            FieldDefinition("category", "Expense Type", "text"),
            FieldDefinition("counterparty", "Counterparty / Vendor", "text"),
            FieldDefinition("suite", "Suite / Location", "text"),
            FieldDefinition("amount", "Amount", "number"),
            FieldDefinition("frequency", "Frequency", "select", True, RECURRING_FREQUENCIES),
            FieldDefinition("startDate", "Start Date", "date"),
            FieldDefinition("nextDueDate", "Next Due Date", "date", True),
            FieldDefinition("lastGeneratedDate", "Last Generated Date", "date"),
            FieldDefinition("priority", "Maintenance Priority", "select", False, MAINTENANCE_PRIORITIES),
            FieldDefinition("activeState", "State", "select", True, ACTIVE_STATES),
            FieldDefinition("notes", "Notes", "textarea"),
        ],
    ),
    "maintenance_records": ModuleDefinition(
        key="maintenance_records",
        label="Maintenance & Work Orders",
        legacy_collection="maintenanceRecords",
        menu_group="Property",
        amount_field="actualCost",
        date_field="reportedDate",
        title_field="issue",
        status_field="status",
        fields=[
            FieldDefinition("reportedDate", "Reported Date", "date", True),
            FieldDefinition("businessAreaId", "Business Area", "select", True, BUSINESS_AREA_OPTIONS),
            FieldDefinition("workOrderNumber", "Work Order Number", "text"),
            FieldDefinition("requestSource", "Request Source", "select", False, MAINTENANCE_REQUEST_SOURCES),
            FieldDefinition("workOrderType", "Work Order Type", "select", False, WORK_ORDER_TYPES),
            FieldDefinition("location", "Location / Suite", "text"),
            FieldDefinition("assetItem", "Asset / Item", "text"),
            FieldDefinition("issue", "Issue / Task", "text", True),
            FieldDefinition("priority", "Priority", "select", True, MAINTENANCE_PRIORITIES),
            FieldDefinition("status", "Status", "select", True, MAINTENANCE_STATUSES),
            FieldDefinition("assignedTo", "Assigned To", "text"),
            FieldDefinition("scheduledDate", "Scheduled Date", "date"),
            FieldDefinition("dueDate", "Due Date", "date"),
            FieldDefinition("completedDate", "Completed Date", "date"),
            FieldDefinition("downtimeHours", "Downtime Hours", "number"),
            FieldDefinition("estimatedCost", "Estimated Cost", "number"),
            FieldDefinition("laborCost", "Labor Cost", "number"),
            FieldDefinition("partsCost", "Parts Cost", "number"),
            FieldDefinition("otherCost", "Other Cost", "number"),
            FieldDefinition("actualCost", "Actual Cost", "number"),
            FieldDefinition("vendor", "Vendor / Technician", "text"),
            FieldDefinition("nextServiceDate", "Next Service Date", "date"),
            FieldDefinition("resolutionSummary", "Resolution Summary", "textarea"),
            FieldDefinition("notes", "Notes", "textarea"),
        ],
    ),
    "knowledge_base": ModuleDefinition(
        key="knowledge_base",
        label="Knowledge Base, SOPs & Staff Training",
        legacy_collection="knowledgeBase",
        menu_group="People",
        amount_field="completionPercent",
        date_field="captureDate",
        title_field="title",
        status_field="status",
        fields=[
            FieldDefinition("captureDate", "Capture Date", "date", True),
            FieldDefinition("businessAreaId", "Business Area", "select", True, BUSINESS_AREA_OPTIONS),
            FieldDefinition("entryType", "Entry Type", "select", True, KNOWLEDGE_ENTRY_TYPES),
            FieldDefinition("title", "Title", "text", True),
            FieldDefinition("audienceRole", "Audience Role", "select", False, KNOWLEDGE_AUDIENCE_OPTIONS),
            FieldDefinition("relatedModule", "Related Module / Process", "text"),
            FieldDefinition("responsiblePerson", "Responsible Person", "text"),
            FieldDefinition("deliveryMode", "Delivery Mode", "select", False, KNOWLEDGE_DELIVERY_MODES),
            FieldDefinition("effectiveDate", "Effective Date", "date"),
            FieldDefinition("reviewDate", "Review Date", "date"),
            FieldDefinition("dueDate", "Training Due Date", "date"),
            FieldDefinition("completionDate", "Completion Date", "date"),
            FieldDefinition("passScore", "Pass Score", "number"),
            FieldDefinition("actualScore", "Actual Score", "number"),
            FieldDefinition("completionPercent", "Completion Percent", "number"),
            FieldDefinition("status", "Status", "select", True, KNOWLEDGE_STATUSES),
            FieldDefinition("notes", "Notes", "textarea"),
        ],
    ),
    "job_vacancies": ModuleDefinition(
        key="job_vacancies",
        label="Job Vacancies",
        legacy_collection="jobVacancies",
        menu_group="People",
        amount_field="openings",
        date_field="postedDate",
        title_field="jobTitle",
        status_field="vacancyStatus",
        fields=[
            FieldDefinition("postedDate", "Posted Date", "date", True),
            FieldDefinition("businessAreaId", "Business Area", "select", True, BUSINESS_AREA_OPTIONS),
            FieldDefinition("jobTitle", "Job Title", "text", True),
            FieldDefinition("staffRole", "Staff Role", "select", False, STAFF_WORK_ROLES),
            FieldDefinition("employmentType", "Employment Type", "select", False, JOB_EMPLOYMENT_TYPES),
            FieldDefinition("vacancyStatus", "Vacancy Status", "select", True, JOB_VACANCY_STATUSES),
            FieldDefinition("openings", "Openings", "number", False, step="1"),
            FieldDefinition("displayOrder", "Display Order", "number", False, step="1"),
            FieldDefinition("location", "Location", "text"),
            FieldDefinition("workingHours", "Working Hours", "textarea"),
            FieldDefinition("closingDate", "Closing Date", "date"),
            FieldDefinition("salaryRange", "Salary Range", "text"),
            FieldDefinition("contactPerson", "Contact Person", "text"),
            FieldDefinition("applicationPhone", "Application Phone", "text"),
            FieldDefinition("applicationEmail", "Application Email", "text"),
            FieldDefinition("applicationLink", "Application Link", "text"),
            FieldDefinition("summary", "Role Summary", "textarea"),
            FieldDefinition("keyResponsibilities", "Key Responsibilities", "textarea"),
            FieldDefinition("requirements", "Requirements", "textarea"),
            FieldDefinition("howToApply", "How To Apply", "textarea"),
            FieldDefinition("notes", "Internal Notes", "textarea"),
        ],
    ),
    "workforce_attendance": ModuleDefinition(
        key="workforce_attendance",
        label="Workforce Scheduling & Attendance",
        legacy_collection="workforceAttendance",
        menu_group="People",
        amount_field="workedHours",
        date_field="shiftDate",
        title_field="staffName",
        status_field="attendanceStatus",
        fields=[
            FieldDefinition("shiftDate", "Shift Date", "date", True),
            FieldDefinition("businessAreaId", "Business Area", "select", True, BUSINESS_AREA_OPTIONS),
            FieldDefinition("staffName", "Staff Name", "text", True),
            FieldDefinition("staffRole", "Shift Role", "select", False, STAFF_WORK_ROLES),
            FieldDefinition("shiftType", "Shift Type", "select", False, SHIFT_TYPES),
            FieldDefinition("shiftStart", "Shift Start", "time"),
            FieldDefinition("shiftEnd", "Shift End", "time"),
            FieldDefinition("checkInTime", "Check-In Time", "time"),
            FieldDefinition("checkOutTime", "Check-Out Time", "time"),
            FieldDefinition("breakMinutes", "Break Minutes", "number", False, step="1"),
            FieldDefinition("scheduledHours", "Scheduled Hours", "number"),
            FieldDefinition("workedHours", "Worked Hours", "number"),
            FieldDefinition("overtimeHours", "Overtime Hours", "number"),
            FieldDefinition("lateMinutes", "Late Minutes", "number", False, step="1"),
            FieldDefinition("attendanceStatus", "Attendance Status", "select", True, ATTENDANCE_STATUSES),
            FieldDefinition("approvalStatus", "Approval Status", "select", False, APPROVAL_STATUSES),
            FieldDefinition("supervisorName", "Supervisor", "text"),
            FieldDefinition("notes", "Notes", "textarea"),
        ],
    ),
    "online_orders": ModuleDefinition(
        key="online_orders",
        label="Online Orders",
        legacy_collection="onlineOrders",
        menu_group="Sales",
        amount_field="quotedTotal",
        date_field="createdAt",
        title_field="orderNumber",
        status_field="status",
        editable=False,
    ),
    "pos_closeouts": ModuleDefinition(
        key="pos_closeouts",
        label="POS Counter Closeouts",
        legacy_collection="posCounterClosures",
        menu_group="Sales",
        amount_field="totalAmount",
        date_field="orderDate",
        title_field="areaLabel",
        editable=False,
    ),
}

LEGACY_TO_MODULE = {definition.legacy_collection: definition.key for definition in MODULES.values()}
MODULE_TO_LEGACY = {definition.key: definition.legacy_collection for definition in MODULES.values()}

MENU_GROUPS = [
    (
        "Workspace",
        [
            ("Overview", ["dashboard", "profits", "category_performance", "reports", "search"]),
            ("Counter & Orders", ["pos", "online_orders", "delivery_dispatch", "workbook"]),
            ("Stock", ["inventory", "inventory_barcode"]),
        ],
    ),
    (
        "Finance",
        [
            ("Sales & Spend", ["sales_summary", "sales", "expenses", "petty_cash", "petty_cash_budgets"]),
            ("Cash & Reconciliation", ["cashbook_entries", "mobile_money_transactions", "mobile_money_reconciliations"]),
        ],
    ),
    (
        "Operations",
        [
            ("Property & Work Orders", ["apartments", "security_deposit_records", "maintenance_records"]),
            ("Service Desk", ["laundry_tickets", "equipment_rental_bookings"]),
        ],
    ),
    (
        "People",
        [
            ("Payroll, Schedules & Training", ["salary_records", "workforce_attendance", "knowledge_base"]),
            ("Recruitment", ["job_vacancies"]),
            ("Suppliers", ["suppliers"]),
        ],
    ),
    (
        "Growth",
        [
            ("Customers & Marketing", ["customer_crm", "promotions", "whatsapp_campaigns", "campaign_roi"]),
        ],
    ),
    (
        "Control",
        [
            ("Planning & Reporting", ["forecast_plans", "recurring_controls", "pos_closeouts"]),
            ("Assets & Admin", ["asset_records", "audit", "users"]),
        ],
    ),
]
